-- seed_curriculum.sql
-- Generated 2025-12-10T08:05:22.786Z

truncate table burburiuok.curriculum_nodes, burburiuok.curriculum_items cascade;

insert into burburiuok.curriculum_nodes (
    code,
    title,
    summary,
    level,
    parent_code,
    ordinal
) values
    ('LBS-1', 'JACHTOS KONSTRUKCIJA, ĮRANGA IR BURLAIVIO TEORIJOS PAGRINDAI (4 val.)', NULL, 1, NULL, 1),
    ('LBS-1-1A', 'Burinių jachtų korpusų tipai', NULL, 2, 'LBS-1', 1),
    ('LBS-1-1-1', 'Burlaivių tipai', NULL, 2, 'LBS-1', 2),
    ('LBS-1-2-1', 'Korpusas', NULL, 2, 'LBS-1', 3),
    ('LBS-1-2-2', 'Rangautas', NULL, 2, 'LBS-1', 4),
    ('LBS-1-2-3', 'Takelažas', NULL, 2, 'LBS-1', 5),
    ('LBS-1-2-4', 'Burių tipai', NULL, 2, 'LBS-1', 6),
    ('LBS-1-3-1', 'Švartavimo ir inkaravimo priemonės', NULL, 2, 'LBS-1', 7),
    ('LBS-1-3-2', 'Avarinės ir gelbėjimo priemonės', NULL, 2, 'LBS-1', 8),
    ('LBS-1-3-3', 'Jachtos pagalbinis mechaninis variklis', NULL, 2, 'LBS-1', 9),
    ('LBS-2', 'BURIAVIMO TEORIJOS PAGRINDAI', NULL, 1, NULL, 2),
    ('LBS-2-1', 'Jachtos charakteristikos', NULL, 2, 'LBS-2', 1),
    ('LBS-2-5', 'Tikrasis vėjas', NULL, 2, 'LBS-2', 2),
    ('LBS-2-6', 'Kursinis vėjas', NULL, 2, 'LBS-2', 3),
    ('LBS-2-7', 'Vimpelinis vėjas', NULL, 2, 'LBS-2', 4),
    ('LBS-3', 'JACHTOS VALDYMO TECHNIKA (6 val.)', NULL, 1, NULL, 3),
    ('LBS-3-4', 'Manevravimo sąvokos', NULL, 2, 'LBS-3', 1),
    ('LBS-3-12-1', 'Vietos parinkimas (inkaravimas)', NULL, 2, 'LBS-3', 2),
    ('LBS-3-15-1', 'Nutrūkus (įrangai)', NULL, 2, 'LBS-3', 3),
    ('LBS-3-15-2', 'Atsikabinus (įrangai)', NULL, 2, 'LBS-3', 4),
    ('LBS-4', 'SAUGOS, GELBĖJIMO, PRIEŠGAISRINĖS PRIEMONĖS, PIRMOJI MEDICINOS PAGALBA (2 val.)', NULL, 1, NULL, 4),
    ('LBS-4-9', 'Pagalbos iškvietimas', NULL, 2, 'LBS-4', 1),
    ('LBS-6', 'NAVIGACIJA, LOCIJA (4 val.)', NULL, 1, NULL, 5),
    ('LBS-6-6', 'Locijos terminai', NULL, 2, 'LBS-6', 1),
    ('LBS-6-11', 'Kliūčių žymėjimo sistemos', NULL, 2, 'LBS-6', 2),
    ('LBS-6-13', 'Darbo su jūrlapiais taisyklės', NULL, 2, 'LBS-6', 3),
    ('LBS-6-14', 'Navigatoriaus-šturmano įrankiai', NULL, 2, 'LBS-6', 4),
    ('LBS-6-15', 'Grafiniai navigaciniai uždaviniai', NULL, 2, 'LBS-6', 5),
    ('LBS-6-16', 'Elektroniniai navigacijos prietaisai', NULL, 2, 'LBS-6', 6),
    ('LBS-7', 'JŪRŲ TEISĖ (4 val.)', NULL, 1, NULL, 6),
    ('LBS-7-2-1', 'Buriavimas pasienio ruože', NULL, 2, 'LBS-7', 1),
    ('LBS-7-2-2', 'Draudimai', NULL, 2, 'LBS-7', 2),
    ('LBS-7-9', 'Vėliavų etiketas', NULL, 2, 'LBS-7', 3),
    ('LBS-8', 'EUROPOS VIDAUS VANDENŲ LAIVYBOS TAISYKLĖS – CEVNI (6 val.)', NULL, 1, NULL, 7),
    ('LBS-8-1', 'Pagrindinės sąvokos', NULL, 2, 'LBS-8', 1),
    ('LBS-8-8', 'Laivų garsinė signalizacija', NULL, 2, 'LBS-8', 2),
    ('LBS-8-9', 'Laivybą reguliuojantys signaliniai ženklai', NULL, 2, 'LBS-8', 3),
    ('LBS-8-10-1', 'Sąvokos', NULL, 2, 'LBS-8', 4),
    ('LBS-9', 'TARPTAUTINĖS TAISYKLĖS LAIVŲ SUSIDŪRIMAMS JŪROJE IŠVENGTI – COLREGS (2 val.)', NULL, 1, NULL, 8),
    ('LBS-9-3', 'Laivų navigaciniai žiburiai ir ženklai', NULL, 2, 'LBS-9', 1),
    ('LBS-10', 'PRAKTINIAI MOKYMAI (12 val.)', NULL, 1, NULL, 9),
    ('LBS-10-17', 'Jūriniai mazgai', NULL, 2, 'LBS-10', 1)

on conflict (code) do update set
    title = excluded.title,
    summary = excluded.summary,
    level = excluded.level,
    parent_code = excluded.parent_code,
    ordinal = excluded.ordinal,
    updated_at = timezone('utc', now());

insert into burburiuok.curriculum_items (
    node_code,
    ordinal,
    label
) values
    ('LBS-1-1A', 1, 'Jolė'),
    ('LBS-1-1A', 2, 'Švertbotas'),
    ('LBS-1-1A', 3, 'Kilinė jachta'),
    ('LBS-1-1A', 4, 'Kompromisas'),
    ('LBS-1-1A', 5, 'Katamaranas'),
    ('LBS-1-1A', 6, 'Trimaranas'),
    ('LBS-1-1A', 7, 'Proa'),
    ('LBS-1-1-1', 1, 'Ketas'),
    ('LBS-1-1-1', 2, 'Šliupas'),
    ('LBS-1-1-1', 3, 'Kuteris (tenderis)'),
    ('LBS-1-1-1', 4, 'Kečas'),
    ('LBS-1-1-1', 5, 'Jolas'),
    ('LBS-1-1-1', 6, 'Škuna'),
    ('LBS-1-1-1', 7, 'Brigantina'),
    ('LBS-1-1-1', 8, 'Brigas'),
    ('LBS-1-1-1', 9, 'Barkentina'),
    ('LBS-1-1-1', 10, 'Barkas'),
    ('LBS-1-1-1', 11, 'Burinis laivas'),
    ('LBS-1-2-1', 1, 'Falškilis'),
    ('LBS-1-2-1', 2, 'Kilis'),
    ('LBS-1-2-1', 3, 'Kilsonas'),
    ('LBS-1-2-1', 4, 'Floras'),
    ('LBS-1-2-1', 5, 'Stepsas'),
    ('LBS-1-2-1', 6, 'Španhautai'),
    ('LBS-1-2-1', 7, 'Stringeriai'),
    ('LBS-1-2-1', 8, 'Knicos'),
    ('LBS-1-2-1', 9, 'Bimsai'),
    ('LBS-1-2-1', 10, 'Pusbimsiai'),
    ('LBS-1-2-1', 11, 'Karlingsai'),
    ('LBS-1-2-1', 12, 'Komingsai'),
    ('LBS-1-2-1', 13, 'Pileriai'),
    ('LBS-1-2-1', 14, 'Švertas (šliūžė)'),
    ('LBS-1-2-1', 15, 'Šverto šulinys'),
    ('LBS-1-2-1', 16, 'Šverto talė'),
    ('LBS-1-2-1', 17, 'Pakabinamasis ir stacionarusis vairas'),
    ('LBS-1-2-1', 18, 'Balansyrinis ir pusiau balansyrinis vairas'),
    ('LBS-1-2-1', 19, 'Forštevenis'),
    ('LBS-1-2-1', 20, 'Achterštevenis'),
    ('LBS-1-2-1', 21, 'Priekinė ir galinė nuosvyros'),
    ('LBS-1-2-1', 22, 'Deidvudas'),
    ('LBS-1-2-1', 23, 'Kairysis bortas'),
    ('LBS-1-2-1', 24, 'Dešinysis bortas'),
    ('LBS-1-2-1', 25, 'Falšbortas'),
    ('LBS-1-2-1', 26, 'Denio sritys'),
    ('LBS-1-2-1', 27, 'Lejeriai'),
    ('LBS-1-2-1', 28, 'Lejerių stovai'),
    ('LBS-1-2-1', 29, 'Forpikas'),
    ('LBS-1-2-1', 30, 'Kajutė'),
    ('LBS-1-2-1', 31, 'Kajutkompanija'),
    ('LBS-1-2-1', 32, 'Achterpikas'),
    ('LBS-1-2-1', 33, 'Triumas'),
    ('LBS-1-2-1', 34, 'Galjūnas (WC)'),
    ('LBS-1-2-1', 35, 'Kambuzas (virtuvė)'),
    ('LBS-1-2-1', 36, 'Variklio skyrius'),
    ('LBS-1-2-1', 37, 'Liukai'),
    ('LBS-1-2-1', 38, 'Iliuminatoriai'),
    ('LBS-1-2-1', 39, 'Ventiliatoriai'),
    ('LBS-1-2-1', 40, 'Vandens tankai'),
    ('LBS-1-2-1', 41, 'Vandens tiekimo sistemos'),
    ('LBS-1-2-1', 42, 'Špigatai'),
    ('LBS-1-2-1', 43, 'Triumo siurbliai'),
    ('LBS-1-2-1', 44, 'Ventiliacijos alsuokliai'),
    ('LBS-1-2-1', 45, 'Deflektoriai'),
    ('LBS-1-2-2', 1, 'Stiebas'),
    ('LBS-1-2-2', 2, 'Gikas'),
    ('LBS-1-2-2', 3, 'Bušpritas'),
    ('LBS-1-2-2', 4, 'Spinakerio gikas'),
    ('LBS-1-2-2', 5, 'Gafelis'),
    ('LBS-1-2-2', 6, 'Pėdos ir nokai, stiebų pavadinimai'),
    ('LBS-1-2-3', 1, 'Forštagai'),
    ('LBS-1-2-3', 2, 'Achterštagai'),
    ('LBS-1-2-3', 3, 'Bakštagai'),
    ('LBS-1-2-3', 4, 'Vantai'),
    ('LBS-1-2-3', 5, 'Talrepai (tempikliai)'),
    ('LBS-1-2-3', 6, 'Falai'),
    ('LBS-1-2-3', 7, 'Šotai'),
    ('LBS-1-2-3', 8, 'Brasai'),
    ('LBS-1-2-3', 9, 'Halsai'),
    ('LBS-1-2-3', 10, 'Rifštertai'),
    ('LBS-1-2-3', 11, 'Topenantai'),
    ('LBS-1-2-3', 12, 'Atotampos'),
    ('LBS-1-2-3', 13, 'Raksai'),
    ('LBS-1-2-3', 14, 'Karabinai'),
    ('LBS-1-2-3', 15, 'Šekeliai (jungės)'),
    ('LBS-1-2-3', 16, 'Blokai (skridiniai)'),
    ('LBS-1-2-3', 17, 'Klampės'),
    ('LBS-1-2-3', 18, 'Fiksatoriai (stoporai)'),
    ('LBS-1-2-3', 19, 'Kipos'),
    ('LBS-1-2-3', 20, 'Putensai'),
    ('LBS-1-2-3', 21, 'Gervės'),
    ('LBS-1-2-3', 22, 'Grotšotų bėgelis su šliaužikliu'),
    ('LBS-1-2-3', 23, 'Stakselšotų ir kiti bėgeliai'),
    ('LBS-1-2-4', 1, 'Tiesioji burė'),
    ('LBS-1-2-4', 2, 'Špritinė burė'),
    ('LBS-1-2-4', 3, 'Gafelinė burė'),
    ('LBS-1-2-4', 4, 'Markoninė (bermudinė) burė'),
    ('LBS-1-2-4', 5, 'Liugerinė burė'),
    ('LBS-1-2-4', 6, 'Huari burė'),
    ('LBS-1-2-4', 7, 'Lotyniška burė'),
    ('LBS-1-2-4', 8, 'Džonko burė'),
    ('LBS-1-2-4', 9, 'Grotas'),
    ('LBS-1-2-4', 10, 'Stakselis'),
    ('LBS-1-2-4', 11, 'Genuja'),
    ('LBS-1-2-4', 12, 'Spinakeris (simetrinis/ asimetrinis)'),
    ('LBS-1-2-4', 13, 'Triselis'),
    ('LBS-1-2-4', 14, 'Audros stakselis'),
    ('LBS-1-2-4', 15, 'Bermudinio groto kampai/kraštinės'),
    ('LBS-1-2-4', 16, 'Boutai'),
    ('LBS-1-2-4', 17, 'Liktrosas'),
    ('LBS-1-2-4', 18, 'Bulinis'),
    ('LBS-1-2-4', 19, 'Liuversai'),
    ('LBS-1-2-4', 20, 'Falo lentelė'),
    ('LBS-1-2-4', 21, 'Latės'),
    ('LBS-1-2-4', 22, 'Lačių kišenės'),
    ('LBS-1-2-4', 23, 'Rifbantai'),
    ('LBS-1-2-4', 24, 'Rifsezeniai'),
    ('LBS-1-2-4', 25, 'Rifštertai'),
    ('LBS-1-3-1', 1, 'Kliuzai'),
    ('LBS-1-3-1', 2, 'Klampės'),
    ('LBS-1-3-1', 3, 'Knechtai'),
    ('LBS-1-3-1', 4, 'Bitengai'),
    ('LBS-1-3-1', 5, 'Žiedai'),
    ('LBS-1-3-1', 6, 'Atmušai (krancai, fenderiai)'),
    ('LBS-1-3-1', 7, 'Priekiniai lynai'),
    ('LBS-1-3-1', 8, 'Galiniai lynai'),
    ('LBS-1-3-1', 9, 'Pripaudžiamieji lynai'),
    ('LBS-1-3-1', 10, 'Špringai'),
    ('LBS-1-3-1', 11, 'Inkarai'),
    ('LBS-1-3-1', 12, 'Inkarų tipai'),
    ('LBS-1-3-1', 13, 'Inkaro lynas'),
    ('LBS-1-3-1', 14, 'Grandinė'),
    ('LBS-1-3-1', 15, 'Suktukas'),
    ('LBS-1-3-1', 16, 'Žvakahalsas'),
    ('LBS-1-3-1', 17, 'Grandinės stabdis'),
    ('LBS-1-3-1', 18, 'Inkaro boja (tomboja)'),
    ('LBS-1-3-1', 19, 'Admiraliteto inkaro kotas'),
    ('LBS-1-3-1', 20, 'Štokas'),
    ('LBS-1-3-1', 21, 'Ragas'),
    ('LBS-1-3-1', 22, 'Letena'),
    ('LBS-1-3-1', 23, 'Inkaro kulnas (trentas)'),
    ('LBS-1-3-2', 1, 'Gesintuvai'),
    ('LBS-1-3-2', 2, 'Kibirai'),
    ('LBS-1-3-2', 3, 'Avarinis rumpelis'),
    ('LBS-1-3-2', 4, 'Įrankiai trosams nukirpti'),
    ('LBS-1-3-2', 5, 'Kūginių kamščių rinkinys'),
    ('LBS-1-3-2', 6, 'Gelbėjimo ratas ir liemenės'),
    ('LBS-1-3-2', 7, 'Saugos diržai'),
    ('LBS-1-3-2', 8, 'Saugos lejeriai'),
    ('LBS-1-3-2', 9, 'Sanitarinės priemonės'),
    ('LBS-1-3-2', 10, 'Navigacinės priemonės'),
    ('LBS-1-3-2', 11, 'Signalizavimo priemonės'),
    ('LBS-1-3-3', 1, 'Variklių rūšys ir paruošimas'),
    ('LBS-1-3-3', 2, 'Priežiūra'),
    ('LBS-2-1', 1, 'Ilgis (LOA)'),
    ('LBS-2-1', 2, 'Plotis (BMAX)'),
    ('LBS-2-1', 3, 'Grimzlė (T)'),
    ('LBS-2-1', 4, 'Vaterlinijos ilgis (LWL)'),
    ('LBS-2-1', 5, 'Laisvo borto aukštis (F)'),
    ('LBS-2-1', 6, 'Vandentalpa'),
    ('LBS-2-1', 7, 'Keliamoji galia'),
    ('LBS-2-1', 8, 'Stovumas'),
    ('LBS-2-1', 9, 'Buringumas'),
    ('LBS-2-1', 10, 'Plūdrumas'),
    ('LBS-2-5', 1, 'Stiprumas (TWS) ir kryptis (TWA)'),
    ('LBS-2-6', 1, 'Sąvoka ir susidarymo priežastis'),
    ('LBS-2-7', 1, 'Kryptis (AWA) ir stiprumas (AWS)'),
    ('LBS-3-4', 1, 'Vendas'),
    ('LBS-3-4', 2, 'Halsas'),
    ('LBS-3-4', 3, 'Kilti'),
    ('LBS-3-4', 4, 'Kristi'),
    ('LBS-3-4', 5, 'Laviruoti'),
    ('LBS-3-4', 6, 'Buriuoti aštriau/bukiau'),
    ('LBS-3-4', 7, 'Dreifuoti'),
    ('LBS-3-4', 8, 'Dreifuoti su burėmis ir be jų'),
    ('LBS-3-4', 9, 'Manevrų komandos'),
    ('LBS-3-12-1', 1, 'Vandens telkinio dugno gruntas'),
    ('LBS-3-12-1', 2, 'Povandeniniai kliuviniai'),
    ('LBS-3-12-1', 3, 'Dugno nuolydis'),
    ('LBS-3-12-1', 4, 'Kranto orientyrai'),
    ('LBS-3-12-1', 5, 'Meteorologiniai aspektai'),
    ('LBS-3-12-1', 6, 'Hidrologiniai aspektai'),
    ('LBS-3-12-1', 7, 'Teisiniai aspektai'),
    ('LBS-3-12-1', 8, 'Urbanistiniai aspektai'),
    ('LBS-3-15-1', 1, 'Priešvėjiniam vantui'),
    ('LBS-3-15-1', 2, 'Bakštagui'),
    ('LBS-3-15-1', 3, 'Forštagui'),
    ('LBS-3-15-1', 4, 'Achterštagui'),
    ('LBS-3-15-1', 5, 'Stakselio falui'),
    ('LBS-3-15-1', 6, 'Groto falui'),
    ('LBS-3-15-2', 1, 'Pavėjiniam vantui'),
    ('LBS-3-15-2', 2, 'Bakštagui'),
    ('LBS-3-15-2', 3, 'Forštagui'),
    ('LBS-3-15-2', 4, 'Achterštagui'),
    ('LBS-3-15-2', 5, 'Stakselio falui'),
    ('LBS-3-15-2', 6, 'Groto falui'),
    ('LBS-4-9', 1, 'Mob. tel. Nr. 112'),
    ('LBS-4-9', 2, 'VHF radijo ryšiu'),
    ('LBS-4-9', 3, 'Gestais matomumo ribose'),
    ('LBS-4-9', 4, 'Signalizacinė pirotechnika'),
    ('LBS-6-6', 1, 'Baseinas'),
    ('LBS-6-6', 2, 'Akvatorija'),
    ('LBS-6-6', 3, 'Sekluma'),
    ('LBS-6-6', 4, 'Sėklius'),
    ('LBS-6-6', 5, 'Baras'),
    ('LBS-6-6', 6, 'RIfas'),
    ('LBS-6-6', 7, 'Bankė'),
    ('LBS-6-6', 8, 'Reidas'),
    ('LBS-6-6', 9, 'Uostas'),
    ('LBS-6-6', 10, 'Avanportas (priešuostis)'),
    ('LBS-6-6', 11, 'Prieplauka'),
    ('LBS-6-6', 12, 'Pirsas'),
    ('LBS-6-6', 13, 'Damba'),
    ('LBS-6-6', 14, 'Molas'),
    ('LBS-6-6', 15, 'Bangolaužis'),
    ('LBS-6-6', 16, 'Kanalas'),
    ('LBS-6-6', 17, 'Farvateris'),
    ('LBS-6-6', 18, 'Gairė'),
    ('LBS-6-6', 19, 'Bakenas'),
    ('LBS-6-6', 20, 'Boja'),
    ('LBS-6-6', 21, 'Švyturys'),
    ('LBS-6-6', 22, 'Pludrusis švyturys'),
    ('LBS-6-6', 23, 'Sektорinis švyturys'),
    ('LBS-6-6', 24, 'Kranto orientyras'),
    ('LBS-6-6', 25, 'Vedlinė'),
    ('LBS-6-11', 1, 'Kardinalinė sistema'),
    ('LBS-6-11', 2, 'Lateralinė ir kiti ženklai'),
    ('LBS-6-13', 1, 'Linijų ilgis'),
    ('LBS-6-13', 2, 'Kampų nustatymas'),
    ('LBS-6-14', 1, 'Matlankis'),
    ('LBS-6-14', 2, 'Lygiagrečioji liniuotė'),
    ('LBS-6-14', 3, 'Skriestuvas-matuoklis'),
    ('LBS-6-15', 1, 'Koordinačių nustatymas'),
    ('LBS-6-15', 2, 'Taško radimas pagal koordinates'),
    ('LBS-6-15', 3, 'Atstumo tarp taškų nustatymas'),
    ('LBS-6-15', 4, 'Tikrojo kurso ar pelengo brėžimas'),
    ('LBS-6-15', 5, 'Nubrėžtos linijos krypties nustatymas'),
    ('LBS-6-16', 1, 'Lagas'),
    ('LBS-6-16', 2, 'Echolotas'),
    ('LBS-6-16', 3, 'Vėjo matuokliai'),
    ('LBS-6-16', 4, 'GPS (stacionari ir mobili)'),
    ('LBS-6-16', 5, 'A.I.S.'),
    ('LBS-6-16', 6, 'Kompasas'),
    ('LBS-7-2-1', 1, 'Straipsniai Nr. 14/1; 7.8'),
    ('LBS-7-2-2', 1, 'Straipsniai Nr. 14/12; 13; 14'),
    ('LBS-7-9', 1, 'Buriuojant'),
    ('LBS-7-9', 2, 'Stovint uoste ar nuleidus inkarą'),
    ('LBS-7-9', 3, 'Plaukiant varikliu'),
    ('LBS-7-9', 4, 'Kitos valstybės vandenyse'),
    ('LBS-8-1', 1, 'Laivas'),
    ('LBS-8-1', 2, 'Laivas su mechaniniu varikliu'),
    ('LBS-8-1', 3, 'Burinis laivas'),
    ('LBS-8-1', 4, 'Greitaeigis laivas'),
    ('LBS-8-1', 5, 'Mažasis laivas'),
    ('LBS-8-1', 6, 'Keltas'),
    ('LBS-8-1', 7, 'Žvejojantis laivas'),
    ('LBS-8-1', 8, 'Laivas stovi'),
    ('LBS-8-1', 9, 'Laivas plaukia'),
    ('LBS-8-1', 10, 'Saugus greitis'),
    ('LBS-8-1', 11, 'Diena'),
    ('LBS-8-1', 12, 'Naktis'),
    ('LBS-8-1', 13, 'Ribotas matomumas'),
    ('LBS-8-1', 14, 'Trumpas garsas'),
    ('LBS-8-1', 15, 'Ilgas garsas'),
    ('LBS-8-1', 16, 'Labai trumpų garsų serija'),
    ('LBS-8-8', 1, 'Garsiniai signalai'),
    ('LBS-8-9', 1, 'Draudžiamieji'),
    ('LBS-8-9', 2, 'Privalomieji'),
    ('LBS-8-9', 3, 'Ribojamieji'),
    ('LBS-8-9', 4, 'Nurodomieji'),
    ('LBS-8-9', 5, 'Informaciniai'),
    ('LBS-8-9', 6, 'Pagalbiniai'),
    ('LBS-8-10-1', 1, 'Plaukimas aukštyn/žemyn'),
    ('LBS-8-10-1', 2, 'Priešpriešinis plaukimas'),
    ('LBS-8-10-1', 3, 'Kursų susikirtimas'),
    ('LBS-8-10-1', 4, 'Lenkimas'),
    ('LBS-9-3', 1, 'Burinis laivas'),
    ('LBS-9-3', 2, 'Laivas su mechaniniu varikliu'),
    ('LBS-9-3', 3, 'Žvejojantis laivas'),
    ('LBS-9-3', 4, 'Velkantis laivas'),
    ('LBS-9-3', 5, 'Vilkstinė'),
    ('LBS-9-3', 6, 'Žemkasė'),
    ('LBS-9-3', 7, 'Stovintis nuleidus inkarą'),
    ('LBS-9-3', 8, 'Ant seklumos'),
    ('LBS-9-3', 9, 'Locmano laivas'),
    ('LBS-9-3', 10, 'Minų traluotojas'),
    ('LBS-10-17', 1, 'Vytulas (virvės suringavimas)'),
    ('LBS-10-17', 2, 'Klampės mazgas'),
    ('LBS-10-17', 3, 'Aštuoniukė'),
    ('LBS-10-17', 4, 'Tikrasis mazgas'),
    ('LBS-10-17', 5, 'Rifo mazgas'),
    ('LBS-10-17', 6, 'Šoto mazgas'),
    ('LBS-10-17', 7, 'Bramšoto mazgas'),
    ('LBS-10-17', 8, 'Paprastasis štekas'),
    ('LBS-10-17', 9, 'Inkaro mazgas'),
    ('LBS-10-17', 10, 'Gelbėjimo kilpa'),
    ('LBS-10-17', 11, 'Buksyravimo mazgas'),
    ('LBS-10-17', 12, 'Žvejų mazgas'),
    ('LBS-10-17', 13, 'Piemenų (veblingo) mazgas'),
    ('LBS-10-17', 14, 'Stoporo mazgas'),
    ('LBS-10-17', 15, 'Plokščiasis mazgas')

on conflict (node_code, ordinal) do update set
    label = excluded.label,
    updated_at = timezone('utc', now());

