-- seed_curriculum.sql
-- Generated 2025-12-03T16:17:23.483Z

insert into burburiuok.curriculum_nodes (
    code,
    title,
    summary,
    level,
    parent_code,
    ordinal
) values
    ('1', 'JACHTOS KONSTRUKCIJA, ĮRANGA IR BURLAIVIO TEORIJOS PAGRINDAI (4 val.)', NULL, 1, NULL, 1),
    ('2', 'BURIAVIMO TEORIJOS PAGRINDAI', NULL, 1, NULL, 2),
    ('3', 'JACHTOS VALDYMO TECHNIKA (6 val.)', NULL, 1, NULL, 3),
    ('4', 'SAUGOS, GELBĖJIMO, PRIEŠGAISRINĖS PRIEMONĖS, PIRMOJI MEDICINOS PAGALBA (2 val.)', NULL, 1, NULL, 4),
    ('5', 'HIDROMETEOROLOGIJA (2 val.)', NULL, 1, NULL, 5),
    ('6', 'NAVIGACIJA, LOCIJA (4 val.)', NULL, 1, NULL, 6),
    ('7', 'JŪRŲ TEISĖ (4 val.)', NULL, 1, NULL, 7),
    ('8', 'EUROPOS VIDAUS VANDENŲ LAIVYBOS TAISYKLĖS – CEVNI (6 val.)', NULL, 1, NULL, 8),
    ('9', 'TARPTAUTINĖS TAISYKLĖS LAIVŲ SUSIDŪRIMAMS JŪROJE IŠVENGTI – COLREGS (2 val.)', NULL, 1, NULL, 9),
    ('10', 'PRAKTINIAI MOKYMAI (12 val.)', NULL, 1, NULL, 10),
    ('1.1', 'Korpusų ir burlaivių tipai', NULL, 2, '1', 1),
    ('1.2', 'Burlaivio sandara', 'korpusas, rangautas, takelažas, burės, burių tipai.', 2, '1', 2),
    ('1.3', 'Jachtos įranga', NULL, 2, '1', 3),
    ('10.1', 'Instruktažas įgulai. Jachtos patikrinimas ir paruošimas plaukti', NULL, 2, '10', 1),
    ('10.2', 'Burių paruošimas išplaukiant', NULL, 2, '10', 2),
    ('10.3', 'Nuplaukimo nuo krantinės, pontono, bojos, kitos plaukiančios jachtos su burėmis arba varikliu būdai esant įvairioms vėjo kryptims ir stiprumui', NULL, 2, '10', 3),
    ('10.4', 'Tinkamas laiko ir vietos parinkimas iškelti ar nuleisti bures išplaukiant bei atplaukiant', NULL, 2, '10', 4),
    ('10.5', 'Pagrindinės saugaus plaukiojimo uoste taisyklės', NULL, 2, '10', 5),
    ('10.6', 'Burių rifavimas', NULL, 2, '10', 6),
    ('10.7', 'Plaukimas aštriais kursais. Posūkiai prieš vėją', NULL, 2, '10', 7),
    ('10.8', 'Plaukimas pavėjiniais kursais. Posūkiai pavėjui', NULL, 2, '10', 8),
    ('10.9', 'Laviruotė prieš vėją ir pavėjui', NULL, 2, '10', 9),
    ('10.10', 'Jachtos valdymas, bendravimas su įgula, komandos plaukiant burėmis įvairiomis oro sąlygomis', NULL, 2, '10', 10),
    ('10.11', 'Manevras „žmogus už borto“ plaukiant burėmis', NULL, 2, '10', 11),
    ('10.12', 'Manevras „žmogus už borto“ plaukiant varikliu', NULL, 2, '10', 12),
    ('10.13', 'Plaukiojimas varikliu, plaukimas varikliu atbuline eiga, sraigto sukimosi įtaka', NULL, 2, '10', 13),
    ('10.14', 'Inkaro naudojimas. Inkaro lyno ar grandinės ilgio parinkimas', NULL, 2, '10', 14),
    ('10.15', 'Priplaukimas prie krantinės, pontono, bojos, kitos jachtos, plaukiančios burėmis, varikliu', NULL, 2, '10', 15),
    ('10.16', 'Švartavimo būdai. Jachtos sutvarkymas po plaukimo', NULL, 2, '10', 16),
    ('10.17', 'Jūriniai mazgai', NULL, 2, '10', 17),
    ('2.1', 'Jachtos charakteristikos', NULL, 2, '2', 1),
    ('2.2', 'Jachtos teorinis brėžinys. Diametralioji plokštuma. Midelšpanhauto plokštuma. Vaterlinijos, batoksai, španhautai. Buringumo centras ir šoninio pasipriešinimo centras', NULL, 2, '2', 2),
    ('2.3', 'Aerodinaminės jėgos susidarymas (kėlimo, traukos, dreifo jėgos, frontinis ir indukcinis pasipriešinimas). Šių jėgų vektorių schema, jachtos centravimas', NULL, 2, '2', 3),
    ('2.4', 'Laminarinis oro srauto aptekėjimas, turbulencijos', NULL, 2, '2', 4),
    ('2.5', 'Tikrasis vėjas', NULL, 2, '2', 5),
    ('2.6', 'Kursinis vėjas', NULL, 2, '2', 6),
    ('2.7', 'Vimpelinis vėjas', NULL, 2, '2', 7),
    ('2.8', 'Vėjo indikatoriai, vėjarodės ir jų veikimo principas', NULL, 2, '2', 8),
    ('3.1', 'Terminai ir sąvokos', NULL, 2, '3', 1),
    ('3.2', 'Jachtos kursai vėjo atžvilgiu. Jachtos kursai pasaulio šalių atžvilgiu', NULL, 2, '3', 2),
    ('3.3', 'Jachtos kursai laivų (burinių ir kitų) atžvilgiu', NULL, 2, '3', 3),
    ('3.4', 'Manevravimo sąvokos', NULL, 2, '3', 4),
    ('3.5', 'Pasiruošimas išplaukti. Jachtos patikrinimas. Jachtos aptakelavimas ir nutakelavimas', NULL, 2, '3', 5),
    ('3.6', 'Jachtos (švertboto ir kilinės) vairavimas. Dreifo mažinimo būdai lengvose ir sunkiose jachtose. Kaip sumažinti kreną ir kaip reguliuoti diferentą', NULL, 2, '3', 6),
    ('3.7', 'Jachtos valdymas vairu ir burėmis. Jachtos valdymas tik burėmis. Jachtos stabdymo būdai. Švertboto valdymo ypatumai', NULL, 2, '3', 7),
    ('3.8', 'Išplaukimas (nuo kranto, prieplaukos, bojos), priplaukimas (prie kranto, prieplaukos, bojos)', NULL, 2, '3', 8),
    ('3.9', 'Manevravimas iškritus žmogui už borto (plaukiant su burėmis). Įgulos veiksmai ir žmogaus iškėlimas iš vandens', NULL, 2, '3', 9),
    ('3.10', 'Žmogaus už borto situacija, jachtos apsisukimas ir grįžimas,', NULL, 2, '3', 10),
    ('3.11', 'Švartavimas', NULL, 2, '3', 11),
    ('3.12', 'Inkaravimas', NULL, 2, '3', 12),
    ('3.13', 'Buriavimas audros sąlygomis', NULL, 2, '3', 13),
    ('3.14', 'Ypatingi plaukiojimo atvejai', NULL, 2, '3', 14),
    ('3.15', 'Avarijos ir jų likvidavimas', NULL, 2, '3', 15),
    ('4.1', 'Saugos planas', NULL, 2, '4', 1),
    ('4.2', 'Buriuotojo apranga', NULL, 2, '4', 2),
    ('4.3', 'Gelbėjimo liemenės ir jų tipai pagal plaukiojimo rajoną. Liemenės komplektacija', NULL, 2, '4', 3),
    ('4.4', 'Gelbėjimo ratai, gelbėjimo pasagos dėvėjimas, metamoji virvė, metamasis žiburys, metamoji boja (angl. danbouy), saugos diržai', NULL, 2, '4', 4),
    ('4.5', 'Gelbėjimo plaustas ir jo pripūtimas, tvarka gelbėjimo plauste', NULL, 2, '4', 5),
    ('4.6', 'Elgesys gelbėjimo operacijos metu (su gelbėtojų kateriu, su gelbėtojų sraigtasparniu)', NULL, 2, '4', 6),
    ('4.7', 'Privalomas jachtos inventorius 4-ai ir 5-ai plaukiojimo kategorijoms', NULL, 2, '4', 7),
    ('4.8', 'Priešgaisrinė sauga', NULL, 2, '4', 8),
    ('4.9', 'Pagalbos iškvietimas', NULL, 2, '4', 9),
    ('4.10', 'Pirmoji medicinos pagalba', NULL, 2, '4', 10),
    ('5.1', 'Atmosferos slėgis, jo kaita ir matavimas', NULL, 2, '5', 1),
    ('5.2', 'Ciklonas, anticiklonas, oro judėjimas juose', NULL, 2, '5', 2),
    ('5.3', 'Orai, oro pablogėjimo požymiai, oro pagerėjimo požymiai, škvalo artėjimo požymiai', NULL, 2, '5', 3),
    ('5.4', 'Rūkas ir migla, jų susidarymas', NULL, 2, '5', 4),
    ('5.5', 'Vėjas (jo susidarymas, matavimas, Boforto skalė). Vėjo stiprumo nustatymas pagal jūros būklę. Gūsis, škvalas, audra, štormas', NULL, 2, '5', 5),
    ('5.6', 'Tipiniai vėjai, vėjų rožė', NULL, 2, '5', 6),
    ('5.7', 'Orų prognozės', NULL, 2, '5', 7),
    ('5.8', 'Bangos, jų susidarymas ir matavimas. Bangavimo skalė', NULL, 2, '5', 8),
    ('5.9', 'Potvynių ir atoslūgių reiškinys. Pagrindinės sąvokos', NULL, 2, '5', 9),
    ('6.1', 'Navigacijos paskirtis ir esmė (naudojami jūrlapiai, jų paskirtis, jūrlapių numeracija, platumos ir ilgumos tinklainių žymėjimai. Šiaurės, Pietų pusrutuliai. Žymėjimo principai, grafinio ženklinimo standartas (INT-1“))', NULL, 2, '6', 1),
    ('6.2', 'Geografinės koordinatės, atstumo, greičio, gylio matavimas laivyboje (matai ir prietaisai)', NULL, 2, '6', 2),
    ('6.3', 'Matomasis horizontas, jo dalijimo sistemos (laipsniai, rumbai). Merkatoriaus projekcija', NULL, 2, '6', 3),
    ('6.4', 'Tikrasis kursas ir pelengas. Magnetinis kompasas ir jo naudojimas', NULL, 2, '6', 4),
    ('6.5', 'Locija. Apibrėžimas. Paskirtis ir turinys', NULL, 2, '6', 5),
    ('6.6', 'Locijos terminai', NULL, 2, '6', 6),
    ('6.7', 'Vidaus vandenų keliai', NULL, 2, '6', 7),
    ('6.8', 'Vidaus vandenų locija', NULL, 2, '6', 8),
    ('6.9', 'Upių locija. Terminai, sąvokos', NULL, 2, '6', 9),
    ('6.10', 'Jūrų locija', NULL, 2, '6', 10),
    ('6.11', 'Kliūčių žymėjimo sistemos', NULL, 2, '6', 11),
    ('6.12', 'Jūrlapiai ir jų skaitymas (INT 1 standartas)', NULL, 2, '6', 12),
    ('6.13', 'Darbo su jūrlapiais taisyklės', NULL, 2, '6', 13),
    ('6.14', 'Navigatoriaus-šturmano įrankiai', NULL, 2, '6', 14),
    ('6.15', 'Grafinių navigacinių uždavinių sprendimas', NULL, 2, '6', 15),
    ('6.16', 'Elektroniniai navigacijos prietaisai', NULL, 2, '6', 16),
    ('6.17', 'Radiolokatoriaus atšvaitas', NULL, 2, '6', 17),
    ('7.1', 'Lietuvos Respublikos Vidaus vandenų transporto kodeksas. Vidaus vandenų kelių sąvoka, kelių naudotojai (6, 7str.), vidaus vandenų transporto priemonių sąvoka, klasifikacija (14, 15 str.), laivų registravimas ir techninė apžiūra (16 str.), burinių jachtų vadų diplomavimas (19.4 str.), laivo kapitono teisės (20 str.), laivo kapitono pareigos kilus pavojui laivui, žmonėms ir gamtai (21 str.), atlyginimas už pagalbos suteikimą (22 str.), vidaus vandenų transporto priemonių plaukiojimo rajonai (24 str.), valstybinė laivybos Lietuvos Respublikos vidaus vandenyse priežiūra (26 str.), Vidaus vandenų transporto priemonių avarijų saugos tyrimo tikslai ir tvarka (27 str.)', NULL, 2, '7', 1),
    ('7.2', 'LIETUVOS RESPUBLIKOS VALSTYBĖS SIENOS IR JOS APSAUGOS ĮSTATYMAS (Suvestinė redakcija nuo 2024-01-01) Sąvokos', 'straipsniai Nr.2/2; 3; 4; 5; 6; 9; 18.', 2, '7', 2),
    ('7.3', 'Klaipėdos valstybinio jūrų uosto laivybos taisyklės (3, 4, 6 str.), uosto akvatorijos ribos (priedas nr.1), laivų greičio ribojimas (50 str.), plaukimas laivybos kanalu (38, 54 str.); draudimas plaukioti uosto akvatorija, esant ribotam matomumui ir stipriam vėjui (56, 57 str.), draudimas plaukioti pramoginiams laivams tam tikrose uosto akvatorijos dalyse (62 str.), laivų prasilenkimas su SGD saugykla ir SGD vežančiais laivais (58, 59 str.), laivų eismo valdymas (60, 61, 63 str.), uosto akvatorijoje galiojantys apribojimai (136, 137 str.). Prasilenkimas su dugno gilintuvais (128, 130 str.), vėliavų etiketas uoste (81str.)', NULL, 2, '7', 3),
    ('7.4', 'Pramoginių laivų uostų taisyklės. Bendras supratimas, ką šios taisyklės reglamentuoja', NULL, 2, '7', 4),
    ('7.5', 'Burinių jachtų registravimo taisyklės. Registravimo tvarka, jachtų žymėjimas', NULL, 2, '7', 5),
    ('7.6', 'Burinių jachtų techninių apžiūrų taisyklės. Bendras supratimas, ką šios taisyklės reglamentuoja', NULL, 2, '7', 6),
    ('7.7', 'Burinių jachtų laivavedžių diplomavimo taisyklės. Laivavedžių kvalifikaciniai laipsniai, jiems keliami reikalavimai ir jų kompetencija', NULL, 2, '7', 7),
    ('7.8', 'Buriavimo etiketas ir jūriniai papročiai', NULL, 2, '7', 8),
    ('7.9', 'Vėliavų etiketas', NULL, 2, '7', 9),
    ('7.10', 'Buriuotojo apranga', NULL, 2, '7', 10),
    ('7.11', 'Ekologiniai reikalavimai, burlaivio ir uosto etiketas', NULL, 2, '7', 11),
    ('7.12', 'Buriuotojo etika', NULL, 2, '7', 12),
    ('8.1', 'Pagrindinės sąvokos', NULL, 2, '8', 1),
    ('8.2', 'Laivavedys, jo ir įgulos narių pareigos. Laivo valdymas', NULL, 2, '8', 2),
    ('8.3', 'Pramoginio laivo dokumentai', NULL, 2, '8', 3),
    ('8.4', 'Gelbėjimas ir pagalbos teikimas', NULL, 2, '8', 4),
    ('8.5', 'Laivavedžio prievolės laivui užplaukus ant seklumos ar nuskendus', NULL, 2, '8', 5),
    ('8.6', 'Laivų ženklinimas', NULL, 2, '8', 6),
    ('8.7', 'Laivų vizualioji signalizacija. Priemonės', 'žiburiai, skydai, vėliavos, gairelės, cilindrai, rutuliai, rombai, kūgiai ir dvigubi kūgiai.', 2, '8', 7),
    ('8.8', 'Laivų garsinė signalizacija', NULL, 2, '8', 8),
    ('8.9', 'Laivybą vandens keliuose reguliuojantys signaliniai ženklai', NULL, 2, '8', 9),
    ('8.10', 'Plaukiojimo taisyklės', NULL, 2, '8', 10),
    ('9.1', 'Bendroji dalis. Atsakomybė. Terminai ir sąvokos. Laivų su mechaniniais varikliais ir burinių laivų teisės', NULL, 2, '9', 1),
    ('9.2', 'Burlaivio prasilenkimas su kitais laivais dieną ir naktį (kursų susikirtimo, priešpriešinio plaukimo ir lenkimo atvejais). Burlaivio prasilenkimas su kitais laivais siaurumose, farvateriuose, laivų judėjimo skyrimo sistemose. Laivų veiksmai užleidžiant kelią. Plaukiojimas riboto matomumo sąlygomis, garso signalai riboto matomumo sąlygomis', NULL, 2, '9', 2),
    ('9.3', 'Laivų navigaciniai žiburiai ir ženklai', NULL, 2, '9', 3),
    ('1.1.1', 'Burinių jachtų korpusų tipai', NULL, 3, '1.1', 1),
    ('1.1.2', 'Burlaivių tipai', NULL, 3, '1.1', 2),
    ('1.2.1', 'Korpusas', NULL, 3, '1.2', 1),
    ('1.2.2', 'Rangautas', NULL, 3, '1.2', 2),
    ('1.2.3', 'Takelažas', NULL, 3, '1.2', 3),
    ('1.2.4', 'Burių tipai', NULL, 3, '1.2', 4),
    ('1.3.1', 'Švartavimo ir inkaravimo priemonės', NULL, 3, '1.3', 1),
    ('1.3.2', 'Avarinės ir gelbėjimo priemonės', NULL, 3, '1.3', 2),
    ('1.3.3', 'Jachtos pagalbinis mechaninis variklis', NULL, 3, '1.3', 3),
    ('1.3.4', 'Variklio naudojimo atvejai jachtoje', NULL, 3, '1.3', 4),
    ('3.11.1', 'Atmušų (krancų, fenderių) vietos ir aukščio parinkimas švartuojantis prie aukštos ir žemos krantinės, lagu prie kito laivo', NULL, 3, '3.11', 1),
    ('3.11.2', 'Švartavimo lyno, jo storio ir ilgio pasirinkimas, apsauga nuo trinties, klampės mazgas', NULL, 3, '3.11', 2),
    ('3.11.3', 'Švartavimo vietos pasirinkimas', NULL, 3, '3.11', 3),
    ('3.11.4', 'Jachtos švartavimas prie krantinės, pontono, šonu (lagu), Šliuze, laivagaliu prie krantinės su inkaru priekyje, keliais bortais', NULL, 3, '3.11', 4),
    ('3.11.5', 'Priplaukimas prie švartavimo vietos, krypties pasirinkimas esant vėjui ir srovei', NULL, 3, '3.11', 5),
    ('3.12.1', 'Vietos parinkimas', NULL, 3, '3.12', 1),
    ('3.12.2', 'Inkaro nuleidimo tvarka ir reikalavimai, komandos ir pranešimai. Inkaro grandinės ilgis', NULL, 3, '3.12', 2),
    ('3.12.3', 'Inkaro iškėlimo tvarka ir reikalavimai, komandos ir pranešimai', NULL, 3, '3.12', 3),
    ('3.13.1', 'Įgulos pasirengimas ir jachtos paruošimas audrai, buringumo mažinimo būdai', NULL, 3, '3.13', 1),
    ('3.13.2', 'Plaukimas naudojant variklį. Manevrų atlikimas naudojant tik variklį', NULL, 3, '3.13', 2),
    ('3.14.1', 'Užplaukimas ant pavėjinės ir priešvėjinės seklumos', NULL, 3, '3.14', 1),
    ('3.14.2', 'Vilkimas (buksyravimas)', NULL, 3, '3.14', 2),
    ('3.14.3', 'Pagalbos suteikimas kitam laivui', NULL, 3, '3.14', 3),
    ('3.14.4', 'Švertboto apvirtimas, atvertimas ir atvertimo technika', NULL, 3, '3.14', 4),
    ('3.15.1', 'Nutrūkus', NULL, 3, '3.15', 1),
    ('3.15.2', 'Atsikabinus', NULL, 3, '3.15', 2),
    ('3.15.3', 'Suplyšus burei', NULL, 3, '3.15', 3),
    ('3.15.4', 'Lūžus stiebui, gikui, gafeliui, rumpeliui, vairo plunksnai, nutrūkus šturtrosams', NULL, 3, '3.15', 4),
    ('3.15.5', 'Pažeidus korpuso hermetiškumą', NULL, 3, '3.15', 5),
    ('4.10.1', 'Laivo vaistinėlės turinys. Naudojimo instrukcija', NULL, 3, '4.10', 1),
    ('4.10.2', 'Sumušimai, kaulų lūžiai, galvos traumos', NULL, 3, '4.10', 2),
    ('4.10.3', 'Žaizdos ir kraujavimas', NULL, 3, '4.10', 3),
    ('4.10.4', 'Nudegimai, saulės smūgis,', NULL, 3, '4.10', 4),
    ('4.10.5', 'Apsinuodijimas maistu', NULL, 3, '4.10', 5),
    ('4.10.6', 'Dirbtinis kvėpavimas ir išorinis širdies masažas', NULL, 3, '4.10', 6),
    ('4.8.1', 'Gesintuvai, jų rūšys galiojimas ir naudojimo taisyklės. Gesintuvų išdėstymo vietos jachtoje', NULL, 3, '4.8', 1),
    ('4.8.2', 'Gaisro gesinimas varikio skyriuje', NULL, 3, '4.8', 2),
    ('4.8.3', 'Elektros instaliacijos sukelto gaisro gesinimas', NULL, 3, '4.8', 3),
    ('4.8.4', 'Kitos priešgaisrinės priemonės. Nedegus audeklas, parankinės priemonės', NULL, 3, '4.8', 4),
    ('7.2.1', 'Buriavimas pasienio ruože', NULL, 3, '7.2', 1),
    ('7.2.2', 'Draudimai', NULL, 3, '7.2', 2),
    ('8.10.1', 'Sąvokos', NULL, 3, '8.10', 1),
    ('8.10.2', 'Laivų prasilenkimas su kitais laivais kursų susikirtimo, priešpriešinio plaukimo ir lenkimo atvejais', NULL, 3, '8.10', 2),
    ('8.10.3', 'Mažųjų laivų prasilenkimas su kitais laivais siaurumose ir vienpusio plaukimo atveju', NULL, 3, '8.10', 3),
    ('8.10.4', 'Laivų prasilenkimas su kitais laivais darant posūkį, išplaukiant ar įplaukiant į uostą ar intaką', NULL, 3, '8.10', 4),
    ('8.10.5', 'Sugretėjusių laivų plaukimas viena kryptimi. Dreifavimas', NULL, 3, '8.10', 5),
    ('8.10.6', 'Plaukimas šliuzais, užtvankomis ir po tiltais', NULL, 3, '8.10', 6),
    ('8.10.7', 'Mažųjų laivų plaukimas riboto matomumo sąlygomis', NULL, 3, '8.10', 7),
    ('8.10.8', 'Ypatingi prioritetai. Laivų prasilenkimas su žvejojančiais ir narus aptarnaujančiais laivais', NULL, 3, '8.10', 8),
    ('8.10.9', 'Laivų stovėjimo taisyklės', NULL, 3, '8.10', 9),
    ('8.7.1', 'Visų tipų laivų eigos ir stovėjimo navigaciniai žiburiai ir ženklai', NULL, 3, '8.7', 1),
    ('8.7.2', 'Specialioji signalizacija (žiburiai ir ženklai)', NULL, 3, '8.7', 2),
    ('1.3.4.1', 'Švartuojantis (judant į priekį ir judant atgaline eiga)', NULL, 4, '1.3.4', 1),
    ('1.3.4.2', 'Lūžus stiebui', NULL, 4, '1.3.4', 2),
    ('1.3.4.3', 'Atliekant manevrus ,,žmogus už borto”', NULL, 4, '1.3.4', 3)

on conflict (code) do update set
    title = excluded.title,
    summary = excluded.summary,
    level = excluded.level,
    parent_code = excluded.parent_code,
    ordinal = excluded.ordinal,
    updated_at = timezone('utc', now());

insert into burburiuok.curriculum_items (
    node_code,
    ordinal,
    label
) values
    ('1.1a', 1, 'jolė'),
    ('1.1a', 2, 'švertbotas'),
    ('1.1a', 3, 'kilinė jachta'),
    ('1.1a', 4, 'kompromisas'),
    ('1.1a', 5, 'katamaranas'),
    ('1.1a', 6, 'trimaranas'),
    ('1.1a', 7, 'proa.'),
    ('1.1.1', 1, 'ketas'),
    ('1.1.1', 2, 'šliupas'),
    ('1.1.1', 3, 'kuteris (tenderis)'),
    ('1.1.1', 4, 'kečas'),
    ('1.1.1', 5, 'jolas'),
    ('1.1.1', 6, 'škuna'),
    ('1.1.1', 7, 'brigantina'),
    ('1.1.1', 8, 'brigas'),
    ('1.1.1', 9, 'barkentina'),
    ('1.1.1', 10, 'barkas'),
    ('1.1.1', 11, 'burinis laivas.'),
    ('1.2.1', 1, 'falškilis'),
    ('1.2.1', 2, 'kilis'),
    ('1.2.1', 3, 'kilsonas'),
    ('1.2.1', 4, 'floras'),
    ('1.2.1', 5, 'stepsas'),
    ('1.2.1', 6, 'španhautai'),
    ('1.2.1', 7, 'stringeriai'),
    ('1.2.1', 8, 'knicos'),
    ('1.2.1', 9, 'bimsai'),
    ('1.2.1', 10, 'pusbimsiai'),
    ('1.2.1', 11, 'karlingsai'),
    ('1.2.1', 12, 'komingsai'),
    ('1.2.1', 13, 'pileriai'),
    ('1.2.1', 14, 'švertas (šliūžė)'),
    ('1.2.1', 15, 'šverto šulinys'),
    ('1.2.1', 16, 'šverto talė'),
    ('1.2.1', 17, 'pakabinamasis ir stacionarusis vairas (skegas, vairo plunksna, vairo dėžė, sorlynis, baleris, vairo galvutė, rumpelis, šturvalas, šturtrosai)'),
    ('1.2.1', 18, 'balansyrinis ir pusiau balansyrinis vairas'),
    ('1.2.1', 19, 'forštevenis'),
    ('1.2.1', 20, 'achterštevenis'),
    ('1.2.1', 21, 'priekinė ir galinė nuosvyros'),
    ('1.2.1', 22, 'deidvudas'),
    ('1.2.1', 23, 'kairysis bortas'),
    ('1.2.1', 24, 'dešinysis bortas'),
    ('1.2.1', 25, 'falšbortas'),
    ('1.2.1', 26, 'denio sritys (bakas, midelis, jutas, kokpitas, kajutės antstatas, falšbortas). Denio dalys: relingai'),
    ('1.2.1', 27, 'lejeriai'),
    ('1.2.1', 28, 'lejerių stovai. Patalpos po deniu: forpikas'),
    ('1.2.1', 29, 'kajutė'),
    ('1.2.1', 30, 'kajutkompanija'),
    ('1.2.1', 31, 'achterpikas'),
    ('1.2.1', 32, 'triumas'),
    ('1.2.1', 33, 'galjunas (WC)'),
    ('1.2.1', 34, 'kambuzas (virtuvė)'),
    ('1.2.1', 35, 'variklio skyrius'),
    ('1.2.1', 36, 'liukai'),
    ('1.2.1', 37, 'iliuminatoriai'),
    ('1.2.1', 38, 'ventiliatoriai'),
    ('1.2.1', 39, 'vandens tankai'),
    ('1.2.1', 40, 'vandens tiekimo sistemos'),
    ('1.2.1', 41, 'špigatai'),
    ('1.2.1', 42, 'triumo siurbliai'),
    ('1.2.1', 43, 'ventiliacijos alsuokliai'),
    ('1.2.1', 44, 'deflektoriai.'),
    ('1.2.2', 1, 'stiebas (stiebo topas, klotikas, pėda, šporas, pertnersas, zalingai)'),
    ('1.2.2', 2, 'gikas'),
    ('1.2.2', 3, 'bušpritas'),
    ('1.2.2', 4, 'spinakerio gikas'),
    ('1.2.2', 5, 'gafelis'),
    ('1.2.2', 6, 'jų pėdos ir nokai. Stiebų pavadinimai.'),
    ('1.2.3', 1, 'nejudamasis (stovimasis) takelažas: forštagai'),
    ('1.2.3', 2, 'achterštagai'),
    ('1.2.3', 3, 'bakštagai'),
    ('1.2.3', 4, 'vantai (topvantai, pagrindiniai vantai)'),
    ('1.2.3', 5, 'talrepai (tempikliai). Judamasis takelažas: falai'),
    ('1.2.3', 6, 'šotai'),
    ('1.2.3', 7, 'brasai'),
    ('1.2.3', 8, 'halsai'),
    ('1.2.3', 9, 'rifštertai'),
    ('1.2.3', 10, 'topenantai'),
    ('1.2.3', 11, 'atotampos (groto giko, spinakerio giko barberio). Takelažo detalės: raksai'),
    ('1.2.3', 12, 'karabinai'),
    ('1.2.3', 13, 'šekeliai (jungės)'),
    ('1.2.3', 14, 'blokai (skridiniai)'),
    ('1.2.3', 15, 'klampės'),
    ('1.2.3', 16, 'fiksatoriai (stoporai)'),
    ('1.2.3', 17, 'kipos'),
    ('1.2.3', 18, 'putensai'),
    ('1.2.3', 19, 'gervės'),
    ('1.2.3', 20, 'grotšotų bėgelis su šliaužikliu'),
    ('1.2.3', 21, 'stakselšotų ir kiti bėgeliai su šliaužikliais.'),
    ('1.2.4', 1, 'tiesioji'),
    ('1.2.4', 2, 'špritinė'),
    ('1.2.4', 3, 'gafelinė'),
    ('1.2.4', 4, 'markoni (bermudinė)'),
    ('1.2.4', 5, 'liugerinė'),
    ('1.2.4', 6, 'huari'),
    ('1.2.4', 7, 'lotyniška'),
    ('1.2.4', 8, 'džonka. Burės: grotas'),
    ('1.2.4', 9, 'stakselis'),
    ('1.2.4', 10, 'genuja (genujietiškas stakselis)'),
    ('1.2.4', 11, 'simetrinis ir asimetrinis spinakeris'),
    ('1.2.4', 12, 'triselis'),
    ('1.2.4', 13, 'audros stakselis. Bermudinio groto konstrukcija: kampų ir kraštinių pavadinimai'),
    ('1.2.4', 14, 'boutai'),
    ('1.2.4', 15, 'liktrosas'),
    ('1.2.4', 16, 'bulinis'),
    ('1.2.4', 17, 'liuversai'),
    ('1.2.4', 18, 'falo lentelė'),
    ('1.2.4', 19, 'latės'),
    ('1.2.4', 20, 'lačių kišenės'),
    ('1.2.4', 21, 'rifbantai'),
    ('1.2.4', 22, 'rifsezeniai'),
    ('1.2.4', 23, 'rifštertai.'),
    ('1.3.1', 1, 'kliuzai'),
    ('1.3.1', 2, 'klampės'),
    ('1.3.1', 3, 'knechtai'),
    ('1.3.1', 4, 'bitengai'),
    ('1.3.1', 5, 'žiedai'),
    ('1.3.1', 6, 'atmušai (krancai, fenderiai)'),
    ('1.3.1', 7, 'priekiniai'),
    ('1.3.1', 8, 'galiniai'),
    ('1.3.1', 9, 'pripaudžiamieji lynai'),
    ('1.3.1', 10, 'špringai'),
    ('1.3.1', 11, 'inkarai'),
    ('1.3.1', 12, 'jų tipai (admiraliteto, Denforto, plūginis, sudedamasis, grybo, sraigtinis, katė, delta)'),
    ('1.3.1', 13, 'inkaro lynas'),
    ('1.3.1', 14, 'grandinė'),
    ('1.3.1', 15, 'suktukas'),
    ('1.3.1', 16, 'žvakahalsas'),
    ('1.3.1', 17, 'grandinės stabdis'),
    ('1.3.1', 18, 'inkaro boja (tomboja). Admiraliteto inkaras: kotas'),
    ('1.3.1', 19, 'štokas'),
    ('1.3.1', 20, 'ragas'),
    ('1.3.1', 21, 'letena'),
    ('1.3.1', 22, 'inkaro kulnas (trentas).'),
    ('1.3.2', 1, 'gesintuvai'),
    ('1.3.2', 2, 'kibirai'),
    ('1.3.2', 3, 'avarinis rumpelis'),
    ('1.3.2', 4, 'įrankiai trosams nukirpti'),
    ('1.3.2', 5, 'kūginių kamščių rinkinys'),
    ('1.3.2', 6, 'gelbėjimo ratas ir liemenės'),
    ('1.3.2', 7, 'saugos diržai'),
    ('1.3.2', 8, 'saugos lejeriai. Avarinių ir gelbėjimo priemonių laikymo jachtoje vietos ir schema. Sanitarinės'),
    ('1.3.2', 9, 'navigacinės'),
    ('1.3.2', 10, 'signalizavimo priemonės.'),
    ('1.3.3', 1, 'variklių rūšys (dyzeliniai, benzininiai, elektriniai). Variklių galingumas. Variklio paruošimas eksploatacijai'),
    ('1.3.3', 2, 'priežiūra.'),
    ('2.1', 1, 'ilgis (LOA)'),
    ('2.1', 2, 'plotis (BMAX)'),
    ('2.1', 3, 'grimzlė (T)'),
    ('2.1', 4, 'vaterlinijos ilgis (LWL)'),
    ('2.1', 5, 'laisvo borto aukštis (F)'),
    ('2.1', 6, 'vandentalpa'),
    ('2.1', 7, 'keliamoji galia'),
    ('2.1', 8, 'stovumas'),
    ('2.1', 9, 'buringumas'),
    ('2.1', 10, 'plūdrumas.'),
    ('2.5', 1, 'stiprumas (TWS) ir kryptis (TWA).'),
    ('2.6', 1, 'sąvoka ir susidarymo priežastis.'),
    ('2.7', 1, 'kryptis (AWA) ir stiprumas (AWS) nustatymas. Susidarymo priežastis ir veikimas.'),
    ('3.4', 1, 'vendas'),
    ('3.4', 2, 'halsas'),
    ('3.4', 3, 'kilti'),
    ('3.4', 4, 'kristi'),
    ('3.4', 5, 'laviruoti'),
    ('3.4', 6, 'buriuoti aštriau/bukiau'),
    ('3.4', 7, 'dreifuoti'),
    ('3.4', 8, 'dreifuoti su burėmis ir be jų'),
    ('3.4', 9, 'manevrų komandos.'),
    ('3.12.1', 1, 'atsižvelgiant į vandens telkinio dugno gruntą'),
    ('3.12.1', 2, 'povandeninius kliuvinius'),
    ('3.12.1', 3, 'dugno nuolydį'),
    ('3.12.1', 4, 'kranto orientyrus'),
    ('3.12.1', 5, 'meteorologinius'),
    ('3.12.1', 6, 'hidrologinius'),
    ('3.12.1', 7, 'teisinius'),
    ('3.12.1', 8, 'urbanistinius aspektus.'),
    ('3.15.1', 1, 'priešvėjiniam vantui'),
    ('3.15.1', 2, 'bakštagui'),
    ('3.15.1', 3, 'forštagui'),
    ('3.15.1', 4, 'achterštagui'),
    ('3.15.1', 5, 'stakselio falui'),
    ('3.15.1', 6, 'groto falui.'),
    ('3.15.2', 1, 'pavėjiniam vantui'),
    ('3.15.2', 2, 'bakštagui'),
    ('3.15.2', 3, 'forštagui'),
    ('3.15.2', 4, 'achterštagui'),
    ('3.15.2', 5, 'stakselio falui'),
    ('3.15.2', 6, 'groto falui.'),
    ('4.9', 1, 'mob. tel. Nr. 112'),
    ('4.9', 2, 'VHF radijo ryšiu'),
    ('4.9', 3, 'gestais matomumo ribose'),
    ('4.9', 4, 'signalizacinė pirotechnika.'),
    ('6.6', 1, 'baseinas'),
    ('6.6', 2, 'akvatorija'),
    ('6.6', 3, 'sekluma'),
    ('6.6', 4, 'sėklius'),
    ('6.6', 5, 'baras'),
    ('6.6', 6, 'rifas'),
    ('6.6', 7, 'bankė'),
    ('6.6', 8, 'reidas'),
    ('6.6', 9, 'uostas'),
    ('6.6', 10, 'avanportas (priešuostis)'),
    ('6.6', 11, 'prieplauka'),
    ('6.6', 12, 'pirsas'),
    ('6.6', 13, 'damba'),
    ('6.6', 14, 'molas'),
    ('6.6', 15, 'bangolaužis'),
    ('6.6', 16, 'kanalas'),
    ('6.6', 17, 'farvateris'),
    ('6.6', 18, 'gairė'),
    ('6.6', 19, 'bakenas'),
    ('6.6', 20, 'boja'),
    ('6.6', 21, 'švyturys'),
    ('6.6', 22, 'pludrusis švyturys'),
    ('6.6', 23, 'sektorinis švyturys'),
    ('6.6', 24, 'kranto orientyras'),
    ('6.6', 25, 'vedlinė.'),
    ('6.11', 1, 'kardinalinė'),
    ('6.11', 2, 'lateralinė ir kiti ženklai.'),
    ('6.13', 1, 'linijų ilgis'),
    ('6.13', 2, 'jų braižymas ir kampų nustatymas.'),
    ('6.14', 1, 'matlankis'),
    ('6.14', 2, 'lygiagrečioji liniuotė'),
    ('6.14', 3, 'skriestuvas-matuoklis.'),
    ('6.15', 1, 'pažymėto jūrlapyje taško koordinačių nustatymas'),
    ('6.15', 2, 'taško radimas jūrlapyje pagal duotas koordinates'),
    ('6.15', 3, 'atstumo tarp dviejų taškų jūrlapyje nustatymas'),
    ('6.15', 4, 'tikrojo kurso ar pelengo brėžimas nuo pažymėto jūrlapyje taško'),
    ('6.15', 5, 'nubrėžtos jūrlapyje linijos krypties nustatymas.'),
    ('6.16', 1, 'lagas'),
    ('6.16', 2, 'echolotas'),
    ('6.16', 3, 'vėjo krypties ir greičio matavimo'),
    ('6.16', 4, 'GPS (stacionari ir mobili)'),
    ('6.16', 5, 'A.I.S. (angl. Automatic Identification System)'),
    ('6.16', 6, 'kompasas.'),
    ('7.2.1', 1, 'straipsniai Nr. 14/1; 7.8.'),
    ('7.2.2', 1, 'straipsniai Nr. 14/12; 13; 14.'),
    ('7.9', 1, 'buriuojant'),
    ('7.9', 2, 'stovint uoste ir nuleidus inkarą'),
    ('7.9', 3, 'plaukiant varikliu'),
    ('7.9', 4, 'būnant kitos valstybės vandenyse.'),
    ('8.1', 1, 'laivas'),
    ('8.1', 2, 'laivas su mechaniniu varikliu'),
    ('8.1', 3, 'burinis laivas'),
    ('8.1', 4, 'greitaeigis laivas'),
    ('8.1', 5, 'mažasis laivas'),
    ('8.1', 6, 'keltas'),
    ('8.1', 7, 'žvejojantis laivas'),
    ('8.1', 8, 'laivas stovi'),
    ('8.1', 9, 'laivas plaukia'),
    ('8.1', 10, 'saugus greitis'),
    ('8.1', 11, 'diena'),
    ('8.1', 12, 'naktis'),
    ('8.1', 13, 'ribotas matomumas'),
    ('8.1', 14, 'trumpas garsas'),
    ('8.1', 15, 'ilgas garsas'),
    ('8.1', 16, 'labai trumpų garsų serija.'),
    ('8.8', 1, 'bendrieji signalai (dėmesio, keičiu savo kursą kairėn, dešinėn, atbulinė eiga, negaliu manevruoti, susidūrimo pavojus); signalai atliekant posūkį; signalai esant ribotam matomumui. Nelaimės pranešimo siganalai.'),
    ('8.9', 1, 'draudžiamieji'),
    ('8.9', 2, 'privalomieji'),
    ('8.9', 3, 'ribojamieji'),
    ('8.9', 4, 'nurodomieji'),
    ('8.9', 5, 'informaciniai'),
    ('8.9', 6, 'pagalbiniai.'),
    ('8.10.1', 1, 'plaukimas aukštyn/žemyn'),
    ('8.10.1', 2, 'priešpriešinis plaukimas'),
    ('8.10.1', 3, 'kursų susikirtimas'),
    ('8.10.1', 4, 'lenkimas.'),
    ('9.3', 1, 'burinio'),
    ('9.3', 2, 'su mechaniniu varikliu'),
    ('9.3', 3, 'žvejojančio'),
    ('9.3', 4, 'velkančio'),
    ('9.3', 5, 'vilkstinės'),
    ('9.3', 6, 'žemkasės'),
    ('9.3', 7, 'stovinčio nuleidus inkarą'),
    ('9.3', 8, 'ant seklumos'),
    ('9.3', 9, 'locmano'),
    ('9.3', 10, 'traluojančio minas. Pagrindiniai garso signalai manevruojant. Nelaimės signalai.'),
    ('10.17', 1, 'vytulas (virvės suringavimas)'),
    ('10.17', 2, 'klampės'),
    ('10.17', 3, 'aštuoniukė'),
    ('10.17', 4, 'tikrasis'),
    ('10.17', 5, 'rifo'),
    ('10.17', 6, 'šoto'),
    ('10.17', 7, 'bramšoto'),
    ('10.17', 8, 'paprastasis štekas'),
    ('10.17', 9, 'inkaro'),
    ('10.17', 10, 'gelbėjimo kilpa'),
    ('10.17', 11, 'buksyravimo'),
    ('10.17', 12, 'žvejų'),
    ('10.17', 13, 'piemenų (veblingo)'),
    ('10.17', 14, 'stoporo'),
    ('10.17', 15, 'plokščiasis.')

on conflict (node_code, ordinal) do update set
    label = excluded.label,
    updated_at = timezone('utc', now());

