-- seed_concepts.sql
-- Generated 2025-10-30T14:10:53.281Z

insert into burburiuok.concepts (
    section_code,
    section_title,
    subsection_code,
    subsection_title,
    slug,
    term_lt,
    term_en,
    description_lt,
    description_en,
    source_ref,
    is_required
) values
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'jole', 'Jolė', 'Dinghy', 'Maža, lengva valties tipo jachta su plokščiu dugnu. Dažnai naudojama mokymuisi ar kaip papildomas laivelis. Lengvai traukiama į krantą.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'svertbotas', 'Švertbotas', 'Centreboard Boat', 'Jachta su keliamu-nuleidžiamu švertu (centreboardu) vietoj nuolatinio kilio. Mažas grimzlimas, tinka sekliam vandeniui.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'kiline-jachta', 'Kilinė jachta', 'Keel Yacht', 'Jachta su fiksuotu, sunkiu falškiliu. Stabili, tinkama jūroms. Didesnis grimzlimas nei šverto.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'kompromisas', 'Kompromisas', 'Bilge Keel', 'Jachta su dviem trumpais kiliais šonuose. Gali stovėti ant dugno atoslūgyje. Vidutinis grimzlimas.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'katamaranas', 'Katamaranas', 'Catamaran', 'Dvikojis laivas - du korpusai sujungti tiltu. Greitas, stabilus, didelis denio plotas. Mažas grimzlimas.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'trimaranas', 'Trimaranas', 'Trimaran', 'Trikojis laivas - centrinis korpusas ir du mažesni šoniniai korpusai (amos). Greitas, lengvas, gera stabilumo sąvoka.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1', 'Korpusų konstrukcijos tipai', 'proa', 'Proa', 'Proa', 'Tradicinis Ramiojo vandenyno dvikojis laivas su nesimetrišku dizainu - vienas korpusas didesnis, kitas ama (stabilizatorius). Vairą lenkia keisdamas kryptį.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'ketas', 'Ketas', 'Cat Rig', 'Viena burė ant vieno stiebo be forštagio. Paprasčiausias rangautas - tik grotas, be priekinės burės.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'sliupas', 'Šliupas', 'Sloop', 'Vienas stiebas, grotas ir priekinė burė (stakselis/genuja). Populiariausias šiuolaikinis rangauto tipas. 90% jachtų.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'kuteris', 'Kuteris (Tenderis)', 'Cutter', 'Vienas stiebas, grotas ir DVI priekinės burės (stakselis + trinkelis). Stiebas dažnai toliau nuo priekio nei šliupe.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'kecas', 'Kečas', 'Ketch', 'Du stiebai: didesnis priekinis (grotstiebis) ir mažesnis galinis (bizanstiebis) PRIEŠ vairą. Bizanburė mažesnė už grotą.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'jolas', 'Jolas', 'Yawl', 'Du stiebai kaip kečas, bet mažas galinis bizanstiebis yra UŽ vairo. Bizanburė labai maža, daugiau balanso nustatymui.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'skuna', 'Škuna', 'Schooner', 'Du ar daugiau stiebų, galinis stiebas AUKŠTESNIS arba lygus priekiniam. Tradicinis prekybinis laivas.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'brigantina', 'Brigantina', 'Brigantine', 'Du stiebai: priekinis su skersėmis ir keturkampėmis burėmis, galinis su markoni (trikampėmis) burėmis.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'brigas', 'Brigas', 'Brig', 'Du stiebai, ant abiejų skersės su keturkampėmis burėmis. Karinis/prekybinis laivas 18-19 amžiuje.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'barkentina', 'Barkentina', 'Barquentine', '3+ stiebai: priekinis su skersėmis (keturkampės burės), kiti su markoni burėmis.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'barkas', 'Barkas', 'Barque', '3+ stiebai: visi išskyrus galinį turi skersės (keturkampės burės), galinis - markoni burė.', NULL, 'LBS 1.1', true),
    ('1.1', 'KORPUSŲ IR BURLAIVIŲ TIPAI', '1.1.1', 'Burlaivių tipai (rangauto tipai)', 'burinis-laivas', 'Burinis laivas', 'Full-rigged Ship', '3+ stiebai, ant visų - skersės su keturkampėmis burėmis. Didžiausi tradiciniai burlaiviai.', NULL, 'LBS 1.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'falskilis', 'Falškilis', 'Ballast Keel', 'Svertas po vandeniu su sunkiu balastiniu galu (švinas/geležis). Suteikia stabilumą ir neleidžia laivui apvirsti ar dreifuoti į šoną.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'kilis', 'Kilis', 'Keel', 'Pagrindinė išilginė korpuso konstrukcija - laivo ''stuburas'', einantis nuo priekio iki galo dugne.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'kilsonas', 'Kilsonas', 'Keelson', 'Vidinis išilginis sutvirtinimas virš kilio, sustiprina korpuso konstrukciją.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'floras', 'Floras', 'Floor Timber', 'Skersinė korpuso konstrukcija dugne, jungia šonus per kilį.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'stepsas', 'Stepsas', 'Mast Step', 'Stiebo tvirtinimo vieta ant kilio ar denio. Priima visą stiebo ir burių apkrovą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'spanhautai', 'Španhautai', 'Frames / Ribs', 'Skersiniai korpuso rėmo elementai - kaip ''šonkauliai'', formuojantys korpuso formą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'stringeriai', 'Stringeriai', 'Stringers', 'Išilginiai sutvirtinimai palei korpusą, jungia španhautus ir sustiprina konstrukciją.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'knicos', 'Knicos', 'Knees', 'Kampiniai tvirtinimai tarp šonų ir denio, sustiprina jungtį.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'bimsai', 'Bimsai', 'Deck Beams', 'Skersiniai denio atramų sijūnai, laikantys denį.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'pusbimsai', 'Pusbimsai', 'Half Beams', 'Pusiau ilgio denio sijūnai, naudojami ten, kur reikia angos (pvz., liukui).', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'karlingsai', 'Karlingsai', 'Carlings', 'Išilginiai denio sijūnai, laikantys denį išilgai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'komingsai', 'Komingsai', 'Coamings', 'Pakelta kokpito ar liuko atrama, saugo nuo vandens patekimo į vidų.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Korpuso konstrukciniai elementai', 'pileriai', 'Pileriai', 'Pillars', 'Vertikalūs denio atramos stulpai kajutėje, perduoda apkrovą nuo denio į kilį.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Šverto sistema', 'svertas', 'Švertas (Šliūžė)', 'Centreboard', 'Keliama-nuleidžiama plokštuma per šverto šulinį, neleidžianti dreifuoti. Šliūžė = daggerboard (vertikaliai ištraukiama).', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Šverto sistema', 'sverto-sulinys', 'Šverto šulinys', 'Centreboard Trunk', 'Vertikali anga korpuse, pro kurią keliamas ir nuleidžiamas švertas.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Šverto sistema', 'sverto-tale', 'Šverto talė', 'Centreboard Pennant', 'Virvė ar trosas, kuriuo keliamas ir nuleidžiamas švertas.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'pakabinamasis-vairas', 'Pakabinamasis vairas', 'Outboard Rudder', 'Vairas, tvirtinamas prie achterštevens galinio krašto pavyzdais (pintles & gudgeons). Lengvai nuimamas.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'stacionarusis-vairas', 'Stacionarusis vairas', 'Inboard Rudder', 'Vairas, integruotas į korpuso konstrukciją, vairo ašis eina per korpusą. Tvirtesnis, tinkamas jūrai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'skegas', 'Skegas', 'Skeg', 'Stacionari vertikali plokštuma prieš vairą, sustiprina vairo sistemą ir pagerina stabilumą kurse.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'vairo-plunksna', 'Vairo plunksna', 'Rudder Blade', 'Besisukanti vairo dalis vandenyje, plokščia plokštuma, kuri keičia vandens srautą ir valdo laivą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'vairo-deze', 'Vairo dėžė', 'Rudder Trunk', 'Korpuse esanti vairo mechanizmo dalis su sandarinimais, kur eina sorlynis.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'sorlynis', 'Sorlynis', 'Rudder Stock', 'Vairo ašis, einanti per korpusą ir jungiantis vairo plunksną su valdymo mechanizmu.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'baleris', 'Baleris', 'Tiller Arm', 'Svertas ant sorlyno denyje, perduodantis jėgą nuo rumpelio ar šturvalo į vairą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'vairo-galvute', 'Vairo galvutė', 'Rudder Head', 'Viršutinė sorlyno dalis, kur tvirtinamas valdymo mechanizmas.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'rumpelis', 'Rumpelis', 'Tiller', 'Horizontalus svertas tiesiogiam vairo valdymui. Paprastas, patikimas, dažnai mažose jachtose iki 30''.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'sturvalas', 'Šturvalas', 'Wheel / Helm', 'Vairo ratas vairo valdymui per šturtrosus arba hidrauliką. Naudojamas didesnėse jachtose.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'sturtrosai', 'Šturtrosai', 'Steering Cables', 'Trosai ar grandinė, sujungiantys šturvą su vairo mechanizmu.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'balansyrinis-vairas', 'Balansyrinis vairas', 'Balanced Rudder', 'Vairas, kurio dalis yra PRIEŠ ašį. Sumažina valdomą jėgą, lengviau valdyti.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Vairo sistema', 'pusiau-balansyrinis-vairas', 'Pusiau balansyrinis vairas', 'Semi-balanced Rudder', 'Vairas su nedidele priekine dalimi už ašies. Kompromisas tarp balanso ir efektyvumo.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'relingai', 'Relingai', 'Lifelines', 'Trosai ar virvės palei denio kraštą, saugantys įgulą nuo kritimo į vandenį. Tvirtinami prie lejerių stovų.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'lejeriai', 'Lejeriai', 'Stanchions', 'Vertikalūs metaliniai stulpeliai palei denį, per kuriuos eina relingai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'lejeriu-stovai', 'Lejerių stovai', 'Stanchion Bases', 'Lejerių tvirtinimo bazės ant denio ar falšborto.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'forpikas', 'Forpikas', 'Forepeak', 'Priekinė patalpa jachtoje už forštevens. Dažnai saugoma inkarai, lynai, burės.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'kajute', 'Kajutė', 'Cabin', 'Gyvenamoji erdvė po deniu su lovomis, stalu. Pagrindinė patogumų vieta.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'kajutkompanija', 'Kajutkompanija', 'Saloon', 'Pagrindinė bendra erdvė - valgomasis su stalu, suoliukais. Socialinė vieta.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'achterpikas', 'Achterpikas', 'Aft Cabin', 'Galinė patalpa už kajutės arba saugykla po kokpitu. Saugomi įrankiai, atsarginės dalys.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'triumas', 'Triumas', 'Bilge', 'Žemiausia vidaus vieta korpuse, kur renkasi vanduo. Čia dažnai siurbliai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'galjunas', 'Galjunas (WC)', 'Head', 'Tualetas jachtoje. Paprastai su unituazu ir kriaukle.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'kambuzas', 'Kambuzas (Virtuvė)', 'Galley', 'Virtuvė jachtoje su virykle, kriaukle, šaldytuvu.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'variklio-skyrius', 'Variklio skyrius', 'Engine Compartment', 'Atskirta erdvė varikliui. Su garso izoliacija, ventiliacija.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'liukai', 'Liukai', 'Hatches', 'Atidaromi denio dangčiai, leidžiantys patekti į vidų. Pagrindinė įėjimo vieta.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'iliuminatoriai', 'Iliuminatoriai', 'Portholes', 'Apvalūs ar ovalūs langai korpuse. Leidžia šviesą ir vėdinimą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'ventiliatoriai', 'Ventiliatoriai', 'Ventilators', 'Vėdinimo sistemos įtaisai denio, leidžiantys orui cirkuliuoti be vandens patekimo.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'vandens-tankai', 'Vandens tankai', 'Water Tanks', 'Gėlo vandens saugojimo talpyklos korpuse. Paprastai kelių šimtų litrų.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'vandens-tiekimo-sistemos', 'Vandens tiekimo sistemos', 'Water System', 'Pompos, vamzdžiai, filtrai gėlo vandens tiekimui į kriaušles ir dušą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'spigatai', 'Špigatai', 'Scuppers', 'Vandens nubėgimo angos kokpite ir denyje. Leidžia vandeniui ištekėti už borto.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'triumo-siurbliai', 'Triumo siurbliai', 'Bilge Pumps', 'Rankiniai ar elektriniai siurbliai triumo vandeniui išpumpuoti. Būtini saugumui.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'ventiliacijos-alsuokliai', 'Ventiliacijos alsuokliai', 'Dorade Vents', 'Specialūs vėdinimo įtaisai su vandens gaudyklėmis. Klasikinis dizainas.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'deflektoriai', 'Deflektoriai', 'Cowl Vents', 'Besisukantys vėjo gaudyklės vėdinimui. Orientuojasi į vėją automatiškai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'relingai-2', 'Relingai', 'Lifelines', 'Trosai ar virvės palei denio kraštą, saugantys įgulą nuo kritimo į vandenį. Tvirtinami prie lejerių stovų.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'lejeriai-2', 'Lejeriai', 'Stanchions', 'Vertikalūs metaliniai stulpeliai palei denį, per kuriuos eina relingai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Denio dalys', 'lejeriu-stovai-2', 'Lejerių stovai', 'Stanchion Bases', 'Lejerių tvirtinimo bazės ant denio ar falšborto.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'forpikas-2', 'Forpikas', 'Forepeak', 'Priekinė patalpa jachtoje už forštevens. Dažnai saugoma inkarai, lynai, burės.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'kajute-2', 'Kajutė', 'Cabin', 'Gyvenamoji erdvė po deniu su lovomis, stalu. Pagrindinė patogumų vieta.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'kajutkompanija-2', 'Kajutkompanija', 'Saloon', 'Pagrindinė bendra erdvė - valgomasis su stalu, suoliukais. Socialinė vieta.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'achterpikas-2', 'Achterpikas', 'Aft Cabin', 'Galinė patalpa už kajutės arba saugykla po kokpitu. Saugomi įrankiai, atsarginės dalys.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'triumas-2', 'Triumas', 'Bilge', 'Žemiausia vidaus vieta korpuse, kur renkasi vanduo. Čia dažnai siurbliai.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'galjunas-2', 'Galjunas (WC)', 'Head', 'Tualetas jachtoje. Paprastai su unituazu ir kriaukle.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'kambuzas-2', 'Kambuzas (Virtuvė)', 'Galley', 'Virtuvė jachtoje su virykle, kriaukle, šaldytuvu.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'variklio-skyrius-2', 'Variklio skyrius', 'Engine Compartment', 'Atskirta erdvė varikliui. Su garso izoliacija, ventiliacija.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'liukai-2', 'Liukai', 'Hatches', 'Atidaromi denio dangčiai, leidžiantys patekti į vidų. Pagrindinė įėjimo vieta.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'iliuminatoriai-2', 'Iliuminatoriai', 'Portholes', 'Apvalūs ar ovalūs langai korpuse. Leidžia šviesą ir vėdinimą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'ventiliatoriai-2', 'Ventiliatoriai', 'Ventilators', 'Vėdinimo sistemos įtaisai denio, leidžiantys orui cirkuliuoti be vandens patekimo.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'vandens-tankai-2', 'Vandens tankai', 'Water Tanks', 'Gėlo vandens saugojimo talpyklos korpuse. Paprastai kelių šimtų litrų.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'vandens-tiekimo-sistemos-2', 'Vandens tiekimo sistemos', 'Water System', 'Pompos, vamzdžiai, filtrai gėlo vandens tiekimui į kriaušles ir dušą.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'spigatai-2', 'Špigatai', 'Scuppers', 'Vandens nubėgimo angos kokpite ir denyje. Leidžia vandeniui ištekėti už borto.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'triumo-siurbliai-2', 'Triumo siurbliai', 'Bilge Pumps', 'Rankiniai ar elektriniai siurbliai triumo vandeniui išpumpuoti. Būtini saugumui.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'ventiliacijos-alsuokliai-2', 'Ventiliacijos alsuokliai', 'Dorade Vents', 'Specialūs vėdinimo įtaisai su vandens gaudyklėmis. Klasikinis dizainas.', NULL, 'LBS 1.2.1', true),
    ('1.2.1', 'KORPUSAS', NULL, 'Patalpos po deniu', 'deflektoriai-2', 'Deflektoriai', 'Cowl Vents', 'Besisukantys vėjo gaudyklės vėdinimui. Orientuojasi į vėją automatiškai.', NULL, 'LBS 1.2.1', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'stiebas', 'Stiebas', 'Mast', 'Pagrindinė vertikali konstrukcija, laikanti bures. Gali būti medinis, aliuminis ar karboninis.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'stiebo-topas', 'Stiebo topas', 'Masthead', 'Viršutinė stiebo dalis. Čia tvirtinami falai ir zalingai.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'klotikas', 'Klotikas', 'Mast Track', 'Grioveliai stiebe, kuriuose slenka groto liktrosas arba rakso šliaužikliai.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'peda', 'Pėda', 'Mast Heel', 'Apatinė stiebo dalis, tvirtinama į stepsą. Čia dažnai elektros laidai į stiebą.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'sporas', 'Šporas', 'Spinnaker Pole', 'Horizontalus kartis spinakeriui (simetriškai buriai). Tvirtinamas ant stiebo.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'pertnersas', 'Pertnersas', 'Mast Partners', 'Sutvirtinta vieta denyje, kur eina stiebas. Su sandarinimais.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebas ir jo dalys', 'zalingiai', 'Zalingiai (Sprederiai)', 'Spreaders', 'Horizontalūs karčiai ant stiebo, atitolina vantus nuo stiebo ir pagerina kampą.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Kiti rangauto elementai', 'gikas', 'Gikas (Buomas)', 'Boom', 'Horizontalus kartis, tvirtinantis groto apačią. Sukasi apie stiebą ir kontroliuoja burę.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Kiti rangauto elementai', 'buspritas', 'Bušpritas', 'Bowsprit', 'Kartis, išsikišęs už forštevens. Leidžia nešti didesnes priekines bures.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Kiti rangauto elementai', 'spinakerio-gikas', 'Spinakerio gikas', 'Spinnaker Pole', 'Kartis spinakeriui, tvirtinamas ant stiebo, laiko burės kampą.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Kiti rangauto elementai', 'gafelis', 'Gafelis', 'Gaff', 'Viršutinis kartis gafelinėse burėse (keturkampėse). Tvirtinamas prie stiebo.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Kiti rangauto elementai', 'pedos', 'Pėdos', 'Heels', 'Apatinės karčių dalys (giko, gafelio), kur jie tvirtinami prie stiebo.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Kiti rangauto elementai', 'nokai', 'Nokai', 'Ends', 'Galinės karčių dalys (giko, gafelio), toliau nuo stiebo.', NULL, 'LBS 1.2.2', true),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebų pavadinimai daugiastiebių laivų', 'grotstiebis', 'Grotstiebis', 'Mainmast', 'Pagrindinis (aukščiausias) stiebas daugiastiebėse jachtose. Ant jo - grotas.', NULL, 'LBS 1.2.2', false),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebų pavadinimai daugiastiebių laivų', 'forstiebis', 'Forstiebis', 'Foremast', 'Priekinis stiebas (jei jų yra 2+). Dažnai mažesnis už grotštiebį.', NULL, 'LBS 1.2.2', false),
    ('1.2.2', 'RANGAUTAS', NULL, 'Stiebų pavadinimai daugiastiebių laivų', 'bizanstiebis', 'Bizanstiebis', 'Mizzen Mast', 'Galinis stiebas kečo/jolo tipo jachtose. Ant jo - bizanburė.', NULL, 'LBS 1.2.2', false),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'forstagai', 'Forštagai', 'Forestays', 'Trosai nuo stiebo topo į priekį (bušpritą ar forštevens). Laiko stiebą nuo atgalinio pasvyrimo. Ant jo dažnai užkabinamos burės.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'achterstagai', 'Achterštagai', 'Backstays', 'Trosai nuo stiebo topo į galą. Laiko stiebą nuo priekinio pasvyrimo. Gali būti nuolatiniai ar reguliuojami.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'bakstagai', 'Bakštagai', 'Running Backstays', 'Reguliuojami galiniai štagai, kuriuos reikia perlenkti kiekviename halse. Laiko stiebą stabilų.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'vantai', 'Vantai', 'Shrouds', 'Šoniniai trosai nuo stiebo į šonus. Laiko stiebą nuo šoninio pasvyrimo. Kelių lygių (topvantai, pagrindiniai).', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'topvantai', 'Topvantai', 'Cap Shrouds', 'Viršutiniai vantai nuo stiebo topo iki korpuso šonų. Svarbiausias stiebo šoninis palaikymas.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'pagrindiniai-vantai', 'Pagrindiniai vantai', 'Lower Shrouds', 'Žemesni vantai, tvirtinami prie stiebo žemiau. Papildomas šoninis stabilumas.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Nejudamasis (stovimasis) takelažas', 'talrepai', 'Talrepai (Tempikliai)', 'Turnbuckles', 'Reguliavimo mechanizmai nejudamajame takelažo. Leidžia įtempti ar atleisti štagai/vantai.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'falai', 'Falai', 'Halyards', 'Virvės, kuriomis keliamos burės. Grotas turi groto falą, stakselis - stakselio falą ir t.t.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'sotai', 'Šotai', 'Sheets', 'Virvės, valdančios burės kampą. Grotšotas valdo grotą, stakselšotas - stakselį. Traukiant - burė įtempiama.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'brasai', 'Brasai', 'Braces', 'Virvės, kontroliuojančios skersių (yardų) kampą keturkampių burių laivuose.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'halsai', 'Halsai', 'Tacks', 'Virvės, tvirtinančios burės priekinį apatinį kampą (hals-kampą). Kontroliuoja burės padėtį.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'rifstertai', 'Rifštertai', 'Reef Lines', 'Virvės rifų įtempimui. Leidžia sumažinti burės plotą stipriam vėjui.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'topenantai', 'Topenantai', 'Topping Lifts', 'Virvė nuo stiebo topo iki giko galo. Laiko giką pakeltą, kai burė nuleista.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Judamasis takelažas', 'atotampos', 'Atotampos', 'Vangs', 'Virvės, stabdančios giko ar spinakerio giko judėjimą. Groto giko vang, spinakerio giko barberis.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'raksai', 'Raksai', 'Shackles', 'Metalinės jungtys su skląsčiu ir smeigtuku. Jungia trosus, bures, blokus.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'karabinai', 'Karabinai', 'Snap Hooks', 'Greito užkabinimo jungtys su spyruokliniu mechanizmu. Bures, falus.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'sekeliai', 'Šekeliai (Jungės)', 'Shackles', 'Metalinės U formos jungtys su smeigtuku. Naudojamos takelažo sujungimams.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'blokai', 'Blokai (Skridiniai)', 'Blocks', 'Skriemuliai virvių traukimui. Sumažina reikalingą jėgą. Vieno, dviejų ar daugiau ratų.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'klampes', 'Klampės', 'Cleats', 'Įtaisai virvių užfiksavimui. V arba T formos metaliniai ar plastikiniai. Ant denio ar stiebo.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'fiksatoriai', 'Fiksatoriai (Stoporai)', 'Cam Cleats', 'Automatiniai virvių spaustukai su krumpliniais danteliais. Laiko virvę vienakryptiškai.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'kipos', 'Kipos', 'Fairleads', 'Virvių vedimo įtaisai (skylės, kilpos). Keičia virvės kryptį ir mažina trinties.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'putensai', 'Putensai', 'Chainplates', 'Metaliniai tvirtinimo taškai korpuse, prie kurių tvirtinami vantai ir štagai.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'gerves', 'Gervės', 'Winches', 'Besisukantys būgnai virvių traukimui. Su rankena. Įvairių dydžių ir galių.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'grotsotu-begelis-su-sliauzikliu', 'Grotšotų bėgelis su šliaužikliu', 'Mainsheet Traveler', 'Skersinė bėgelio sistema su šliaužikliu, leidžianti grotšotui judėti į šonus ir reguliuoti burės kampą.', NULL, 'LBS 1.2.3', true),
    ('1.2.3', 'TAKELAŽAS', NULL, 'Takelažo detalės ir priedai', 'stakselsotu-ir-kiti-begeliai', 'Stakselšotų ir kiti bėgeliai', 'Jib Tracks', 'Šoniniai bėgeliai stakselio šotų šliaužikliams. Leidžia reguliuoti stakselio traukimo kampą.', NULL, 'LBS 1.2.3', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'tiesioji-bure', 'Tiesioji burė', 'Square Sail', 'Keturkampė burė ant horizontalios skersės. Senovinių laivų burė, efektyvi vėjui iš galo.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'spritine-bure', 'Špritinė burė', 'Spritsail', 'Keturkampė burė su įstriža kartimi (špritu) nuo stiebo apačios į viršutinį galą. Senovinė konstrukcija.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'gafeline-bure', 'Gafelinė burė', 'Gaff Sail', 'Keturkampė burė su gafeliu (viršutiniu kartimi). Tradicinė, didelis ploto plotas.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'markoni', 'Markoni (Bermudinė)', 'Marconi / Bermudian', 'Trikampė burė iki stiebo topo. Šiuolaikinis standartas - efektyvi, paprasta, lengvai valdoma.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'liugerine-bure', 'Liugerinė burė', 'Lugger Sail', 'Keturkampė burė su įstriža skerse, kuri slenka ant stiebo. Lengva valdyti vienai žmogui.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'huari-bure', 'Huari burė', 'Gunter Rig', 'Burė su trumpu gafeliu, kuris iškeltas beveik vertikaliai, imituoja aukštą stiebą.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'lotyniska-bure', 'Lotyniška burė', 'Lateen Sail', 'Trikampė burė ant ilgos įstrižos skersės. Viduržemio jūros tradicinė, gali plaukti arti vėjo.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Burių tipai pagal formą', 'dzonka-bure', 'Džonka burė', 'Junk Rig', 'Kinijos tradicinė burė su horizontaliomis latėmis per visą burę. Labai lengva valdyti, rifinama greitai.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'grotas', 'Grotas', 'Mainsail', 'Pagrindinė burė ant stiebo ir giko. Trikampė (markoni). Labiausiai valdoma burė.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'stakselis', 'Stakselis', 'Jib', 'Priekinė trikampė burė prieš stiebą. Mažesnė nei genuja, nepersikloja su stiebą.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'genuja', 'Genuja', 'Genoa', 'Didelė priekinė burė, kuri persikloja su stiebą. Daugiau galios nei stakselis.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'simetrinis-spinakeris', 'Simetrinis spinakeris', 'Symmetrical Spinnaker', 'Didelė, lengva kupola vėjui iš galo. Simetriška, reikia šporo (kartis). Dažnai spalvota.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'asimetrinis-spinakeris', 'Asimetrinis spinakeris', 'Asymmetrical Spinnaker', 'Asimetriška lengva burė vėjui iš šono/galo. Lengviau valdyti nei simetrinis, nereikia šporo.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'triselis', 'Triselis', 'Trysail', 'Mažas sunkios audros grotas. Be giko, tvirtinamas tiesiai prie stiebo. Naudojamas audroje.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Šiuolaikinės burės', 'audros-stakselis', 'Audros stakselis', 'Storm Jib', 'Mažas, sunkus stakselis audroms. Labai tvirtas, mažas plotas, leidžia valdyti jachtą stipriam vėjui.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'kampai', 'Kampai', 'Corners', 'Trys pagrindiniai burės kampai: halskampis (priekis apačioj), šotakampis (galas), falkampis (viršus).', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'krastines', 'Kraštinės', 'Edges', 'Trys burės kraštai: liktrosas (priekinis), būtė (apačia), falinis (galinis/viršutinis).', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'boutai', 'Boutai (Latės)', 'Battens', 'Ploni elastingi karčiai kišenėse palei galinį burės kraštą. Palaiko formą ir sumažina plevesavimą.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'liktrosas', 'Liktrosas', 'Luff', 'Priekinis burės kraštas, dažnai sustiprintas trosu ar nuaudžiama juosta. Įleidžiama į klotiką.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'bulinis', 'Bulinis', 'Foot', 'Apatinis burės kraštas tarp halskampio ir šotakampio. Dažnai ant giko.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'liuversai', 'Liuversai', 'Grommets', 'Metaliniai žiedai burės kampuose ir kraštais. Per juos eina virvės (falai, šotai).', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'falo-lentele', 'Falo lentelė', 'Headboard', 'Sustiprintas trikampis burės viršuje (falkampyje), kur tvirtinamas falas.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'lates', 'Latės', 'Battens', 'Ploni lankstūs karčiai burės kišenėse. Palaiko burės formą. Pilno ilgio arba trumpos.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'latciu-kisenes', 'Latčių kišenės', 'Batten Pockets', 'Horizontalios kišenės burėje, kur įdedamos latės. Paprastai 3-5 vnt.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'rifbantai', 'Rifbantai', 'Reef Points', 'Horizontalios eilės liuversų arba virvučių burės rifavimui. Leidžia sumažinti burės plotą audroje.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'rifsezeniai', 'Rifsezeniai', 'Reef Cringles', 'Sustiprintos burės vietos su liuversais rifavimo linijoms. Ant burės priekio ir galo.', NULL, 'LBS 1.2.4', true),
    ('1.2.4', 'BURĖS', NULL, 'Bermudinio groto konstrukcija', 'rifstertai-2', 'Rifštertai', 'Reef Lines', 'Virvės, kuriomis įtempiamas rifas - patenka per rifsezenius ir trakuoja burę žemyn.', NULL, 'LBS 1.2.4', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'kliuzai', 'Kliuzai', 'Hawse Pipes', 'Angos arba roleliai forštevenyje, per kuriuos eina inkaro lynai ar grandinė.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'klampes-2', 'Klampės', 'Cleats', 'T arba V formos tvirtinimai lynams ant denio. Metaliniai ar plastikiniai.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'knechtai', 'Knechtai', 'Bollards', NULL, NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'bitengai', 'Bitengai', 'Bitts', 'Dvigubi vertikalūs stulpai lynų tvirtinimui. Tvirtesni už klampės.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'ziedai', 'Žiedai', 'Ring Bolts', 'Metaliniai žiedai švartavimo lynų vedimui ir tvirtinimui.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'atmusai', 'Atmušai (Fenderiai)', 'Fenders', 'Pripučiami ar putplasčio apsaugos pagalvės tarp laivo ir krantinės. Apsaugo korpusą.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'priekiniai-lynai', 'Priekiniai lynai', 'Bow Lines', 'Lynai nuo priekio į krantinę. Laiko laivą prie krantinės.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'galiniai-lynai', 'Galiniai lynai', 'Stern Lines', 'Lynai nuo galo į krantinę. Laiko laivą stabiliai.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'pripaudziamieji-lynai', 'Pripaudžiamieji lynai', 'Breast Lines', 'Lynai statmenai į krantinę, traukia laivą prie krantinės.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.1', 'Švartavimo ir inkaravimo priemonės', 'springai', 'Špringai', 'Spring Lines', 'Įstrižai einantys lynai, neleidžiantys laivui judėti į priekį ar atgal.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'admiraliteto-inkaras', 'Admiraliteto inkaras', 'Admiralty Anchor', 'Klasikinis inkaras su dviem ragais ir skerstiniu štoku. Sunkus, patikimas, bet nepatogus.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'denforto-inkaras', 'Denforto inkaras', 'Danforth Anchor', 'Plokščias inkaras su dviem didelėmis mentelėmis. Gerai laiko smėlyje ir dumbale.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'pluginis-inkaras', 'Plūginis inkaras', 'Plow Anchor', 'Arklo formos inkaras. Universalus, geras įvairiuose dugnuose. Populiarus jachtose.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'sudedamasis-inkaras', 'Sudedamasis inkaras', 'Folding Anchor', 'Inkaras su sulenkiamais ragais. Kompaktiškas saugojimui.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'grybo-inkaras', 'Grybo inkaras', 'Mushroom Anchor', 'Grybo formos inkaras. Geras minkštam dugnui ir ilgalaikiam inkaravimui (bujoms).', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'sraigtinis-inkaras', 'Sraigtinis inkaras', 'Screw Anchor', 'Į dugną įsukamas inkaras. Labai tvirtas, naudojamas nuolatinėms bujoms.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'kate', 'Katė', 'Grapnel Anchor', 'Mažas 4-5 ragų inkaras. Tinka uolėtam dugnui ir mažiems laivams.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkarų tipai', 'delta-inkaras', 'Delta inkaras', 'Delta Anchor', 'Panašus į plūginį, bet viena mentele. Savarankiškai orientuojasi, geras laikymas.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Admiraliteto inkaro dalys', 'kotas', 'Kotas', 'Shank', 'Centrinė inkaro dalis - ilgas vertikalus strypas.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Admiraliteto inkaro dalys', 'stokas', 'Štokas', 'Stock', 'Skersinis kartis viršuje, užtikrinantis teisingą inkaro padėtį dugne.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Admiraliteto inkaro dalys', 'ragas', 'Ragas', 'Fluke', 'Mentelė, įsikabinanti į dugną. Admiraliteto inkaras turi du ragus.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Admiraliteto inkaro dalys', 'letena', 'Letena', 'Crown', 'Apatin inkaro dalis, kur susijungia ragas ir kotas.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Admiraliteto inkaro dalys', 'inkaro-kulnas', 'Inkaro kulnas (Trentas)', 'Bill', 'Aštrūs ragų galai, įsikabinantys į dugną.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkaravimo įranga', 'inkaro-lynas', 'Inkaro lynas', 'Anchor Rode', 'Virvė, jungianti inkarą su laivu. Nailoninis, elastingas.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkaravimo įranga', 'grandine', 'Grandinė', 'Anchor Chain', 'Metalinė grandinė tarp inkaro ir lyno arba vietoj lyno. Sunkesnė, tvirtesnė.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkaravimo įranga', 'suktukas', 'Suktukas', 'Windlass', 'Rankinis ar elektrinis mechanizmas inkaro kėlimui. Ant denio forštevenyje.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkaravimo įranga', 'zvakahalsas', 'Žvakahalsas', 'Anchor Shackle', 'Tvirtinimo jungtis tarp inkaro ir grandinės/lyno.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkaravimo įranga', 'grandines-stabdis', 'Grandinės stabdis', 'Chain Stopper', 'Mechanizmas grandinei užfiksuoti, kad ji neslidtų.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', NULL, 'Inkaravimo įranga', 'inkaro-boja', 'Inkaro boja (Tomboja)', 'Anchor Buoy', 'Plūdė, pažyminti inkaro vietą vandenyje. Padeda rasti inkarą.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'gesintuvai', 'Gesintuvai', 'Fire Extinguishers', 'Gaisro gesintuvai. Privalomi jachtose, kelių tipų (miltelių, CO2). Privalo būti prieinami.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'kibirai', 'Kibirai', 'Buckets', 'Kibirai vandeniui semti avarijoje ar gaisrui gesinti. Paprastas, bet efektyvus įrankis.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'avarinis-rumpelis', 'Avarinis rumpelis', 'Emergency Tiller', 'Atsarginis vairo valdymo svertas, jei pagrindinė sistema suges.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'irankiai-trosams-nukirpti', 'Įrankiai trosams nukirpti', 'Wire Cutters', 'Stiprūs žirklės ar peilis trosų karpymui avarijoje.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'kuginiu-kamsciu-rinkinys', 'Kūginių kamščių rinkinys', 'Wooden Plugs', 'Medinikeliū kamščiai skylių korpuse užkimšimui avarijoje.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'gelbejimo-ratas', 'Gelbėjimo ratas', 'Lifebuoy', 'Plūduriuojantis ratas su virve. Mėtomas žmogui vandenyje.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'gelbejimo-liemenes', 'Gelbėjimo liemenės', 'Life Jackets', 'Asmeninės plūduriavimo priemonės. Privalo būti kiekvienam įgulos nariui.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'saugos-dirzai', 'Saugos diržai', 'Safety Harnesses', 'Diržai su trosais prie laivo pririšimui stipriame vėjyje ar bangose.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.2', 'Avarinės ir gelbėjimo priemonės', 'saugos-lejeriai', 'Saugos lejeriai', 'Jacklines', 'Trosai išilgai denio, prie kurių kabinami saugos diržai.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.3', 'Pagalbinis variklis', 'dyzeliniai-varikliai', 'Dyzeliniai varikliai', 'Diesel Engines', 'Dyzeliu varomi varikliai. Ekonomiški, patikimi, dažniausias pasirinkimas jachtoms.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.3', 'Pagalbinis variklis', 'benzininiai-varikliai', 'Benzininiai varikliai', 'Gasoline Engines', 'Benzinu varomi varikliai. Lengvesni, pigesni, bet pavojingesni (garai).', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.3', 'Pagalbinis variklis', 'elektriniai-varikliai', 'Elektriniai varikliai', 'Electric Motors', 'Elektra varomi varikliai. Tylūs, ekologiški, bet ribotas nuotolis.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.3', 'Pagalbinis variklis', 'varikliu-galingumas', 'Variklių galingumas', 'Engine Power', 'Matuojamas arklio galiomis (AG) arba kilovatais (kW). Priklauzo nuo jachtos dydžio.', NULL, 'LBS 1.3', true),
    ('1.3', 'JACHTOS ĮRANGA', '1.3.3', 'Pagalbinis variklis', 'variklio-prieziura', 'Variklio priežiūra', 'Engine Maintenance', 'Reguliarus alyvos keitimas, filtrų valymas, aušinimo sistemos tikrinimas.', NULL, 'LBS 1.3', true)

on conflict (slug) do update set
    section_code = excluded.section_code,
    section_title = excluded.section_title,
    subsection_code = excluded.subsection_code,
    subsection_title = excluded.subsection_title,
    term_lt = excluded.term_lt,
    term_en = excluded.term_en,
    description_lt = excluded.description_lt,
    description_en = excluded.description_en,
    source_ref = excluded.source_ref,
    is_required = excluded.is_required,
    updated_at = timezone('utc', now());

